-- Add popular players to Supabase
INSERT INTO players (id, full_name, country, role) VALUES
  ('KAPILDEV', 'Kapil Dev', 'India', 'All-rounder'),
  ('SUNILGAVASKAR', 'Sunil Gavaskar', 'India', 'Batsman'),
  ('MOHAMMADAZHAR', 'Mohammad Azharuddin', 'India', 'Batsman'),
  ('DILIPVENGSARKAR', 'Dilip Vengsarkar', 'India', 'Batsman'),
  ('JAVAGALSRINATH', 'Javagal Srinath', 'India', 'Bowler'),
  ('VENKATESHPRASAD', 'Venkatesh Prasad', 'India', 'Bowler'),
  ('NAYANMONGIA', 'Nayan Mongia', 'India', 'Wicketkeeper'),
  ('VINODKAMBLI', 'Vinod Kambli', 'India', 'Batsman'),
  ('AJAYJ', 'Ajay Jadeja', 'India', 'All-rounder'),
  ('ROBINUTHAPPA', 'Robin Uthappa', 'India', 'Wicketkeeper'),
  ('PUJARA', 'Cheteshwar Pujara', 'India', 'Batsman'),
  ('ISHANKISHAN', 'Ishan Kishan', 'India', 'Wicketkeeper'),
  ('YUZVENDRACHAHAL', 'Yuzvendra Chahal', 'India', 'Bowler'),
  ('MANISHPANDEY', 'Manish Pandey', 'India', 'Batsman'),
  ('AMBATIRAYUDU', 'Ambati Rayudu', 'India', 'Batsman'),
  ('KEDARJADHAV', 'Kedar Jadhav', 'India', 'All-rounder'),
  ('DINESHKARTHIK', 'Dinesh Karthik', 'India', 'Wicketkeeper'),
  ('IMRANKHAN', 'Imran Khan', 'Pakistan', 'All-rounder'),
  ('JAVEDMIANDAD', 'Javed Miandad', 'Pakistan', 'Batsman'),
  ('SHOAIBAKHTAR', 'Shoaib Akhtar', 'Pakistan', 'Bowler'),
  ('SAIDFANWAR', 'Saeed Anwar', 'Pakistan', 'Batsman'),
  ('YOUNIS', 'Younis Khan', 'Pakistan', 'Batsman'),
  ('MISBAH', 'Misbah-ul-Haq', 'Pakistan', 'Batsman'),
  ('STEVEWAUGH', 'Steve Waugh', 'Australia', 'All-rounder'),
  ('MARKWAUGH', 'Mark Waugh', 'Australia', 'Batsman'),
  ('ALLANBORDR', 'Allan Border', 'Australia', 'Batsman'),
  ('DENNISLILLEE', 'Dennis Lillee', 'Australia', 'Bowler'),
  ('BRETTLEE', 'Brett Lee', 'Australia', 'Bowler'),
  ('JASONGILLESP', 'Jason Gillespie', 'Australia', 'Bowler'),
  ('IANBOTHAM', 'Ian Botham', 'England', 'All-rounder'),
  ('GRAHAMGOOCH', 'Graham Gooch', 'England', 'Batsman'),
  ('ALECCOOK', 'Alastair Cook', 'England', 'Batsman'),
  ('JAMANDERSON', 'James Anderson', 'England', 'Bowler'),
  ('STUARTBROAD', 'Stuart Broad', 'England', 'Bowler'),
  ('PAULCOLLINGWOOD', 'Paul Collingwood', 'England', 'All-rounder'),
  ('ALLANDONALD', 'Allan Donald', 'South Africa', 'Bowler'),
  ('HANSIECRONJE', 'Hansie Cronje', 'South Africa', 'All-rounder'),
  ('JONTYRHODES', 'Jonty Rhodes', 'South Africa', 'Batsman'),
  ('LANCEKLUSENER', 'Lance Klusener', 'South Africa', 'All-rounder'),
  ('DALESTEYN', 'Dale Steyn', 'South Africa', 'Bowler'),
  ('MLORANI', 'Morne Morkel', 'South Africa', 'Bowler'),
  ('VIVIDRICHARDS', 'Viv Richards', 'West Indies', 'Batsman'),
  ('GORDONGREENI', 'Gordon Greenidge', 'West Indies', 'Batsman'),
  ('DESMONDHAYNE', 'Desmond Haynes', 'West Indies', 'Batsman'),
  ('MICHAELHOLDING', 'Michael Holding', 'West Indies', 'Bowler'),
  ('ANDYROBERTS', 'Andy Roberts', 'West Indies', 'Bowler'),
  ('ARJUNARANATUNGA', 'Arjuna Ranatunga', 'Sri Lanka', 'Batsman'),
  ('ARAVINDADESILVA', 'Aravinda de Silva', 'Sri Lanka', 'Batsman'),
  ('ROMESHKALUWITHARANA', 'Romesh Kaluwitharana', 'Sri Lanka', 'Wicketkeeper'),
  ('TILLAKARATNE', 'Tillakaratne Dilshan', 'Sri Lanka', 'All-rounder'),
  ('RICHARDHADLEE', 'Richard Hadlee', 'New Zealand', 'All-rounder'),
  ('MARTINCROWE', 'Martin Crowe', 'New Zealand', 'Batsman'),
  ('STEPHFLEMING', 'Stephen Fleming', 'New Zealand', 'Batsman'),
  ('CHRISCAIRNS', 'Chris Cairns', 'New Zealand', 'All-rounder'),
  ('ROSST', 'Ross Taylor', 'New Zealand', 'Batsman'),
  ('RASHIDKHANSPIN', 'Rashid Khan', 'Afghanistan', 'Bowler'),
  ('MUJEEBZADRAN', 'Mujeeb Ur Rahman', 'Afghanistan', 'Bowler');