-- Add popular players to Supabase
INSERT INTO players (id, full_name, country, role) VALUES
  ('KAPILDEV', 'Kapil Dev', 'India', 'All-rounder'),
  ('SUNILGAVASKAR', 'Sunil Gavaskar', 'India', 'Batsman'),
  ('MOHAMMADAZHAR', 'Mohammad Azharuddin', 'India', 'Batsman'),
  ('DILIPVENGSARKAR', 'Dilip Vengsarkar', 'India', 'Batsman'),
  ('JAVAGALSRINATH', 'Javagal Srinath', 'India', 'Bowler'),
  ('VENKATESHPRASAD', 'Venkatesh Prasad', 'India', 'Bowler'),
  ('NAYANMONGIA', 'Nayan Mongia', 'India', 'Wicketkeeper'),
  ('VINODKAMBLI', 'Vinod Kambli', 'India', 'Batsman'),
  ('AJAYJ', 'Ajay Jadeja', 'India', 'All-rounder'),
  ('ROBINUTHAPPA', 'Robin Uthappa', 'India', 'Wicketkeeper'),
  ('PUJARA', 'Cheteshwar Pujara', 'India', 'Batsman'),
  ('ISHANKISHAN', 'Ishan Kishan', 'India', 'Wicketkeeper'),
  ('YUZVENDRACHAHAL', 'Yuzvendra Chahal', 'India', 'Bowler'),
  ('MANISHPANDEY', 'Manish Pandey', 'India', 'Batsman'),
  ('AMBATIRAYUDU', 'Ambati Rayudu', 'India', 'Batsman'),
  ('KEDARJADHAV', 'Kedar Jadhav', 'India', 'All-rounder'),
  ('DINESHKARTHIK', 'Dinesh Karthik', 'India', 'Wicketkeeper'),
  ('IMRANKHAN', 'Imran Khan', 'Pakistan', 'All-rounder'),
  ('JAVEDMIANDAD', 'Javed Miandad', 'Pakistan', 'Batsman'),
  ('SHOAIBAKHTAR', 'Shoaib Akhtar', 'Pakistan', 'Bowler'),
  ('SAIDFANWAR', 'Saeed Anwar', 'Pakistan', 'Batsman'),
  ('YOUNIS', 'Younis Khan', 'Pakistan', 'Batsman'),
  ('MISBAH', 'Misbah-ul-Haq', 'Pakistan', 'Batsman'),
  ('STEVEWAUGH', 'Steve Waugh', 'Australia', 'All-rounder'),
  ('MARKWAUGH', 'Mark Waugh', 'Australia', 'Batsman'),
  ('ALLANBORDR', 'Allan Border', 'Australia', 'Batsman'),
  ('DENNISLILLEE', 'Dennis Lillee', 'Australia', 'Bowler'),
  ('BRETTLEE', 'Brett Lee', 'Australia', 'Bowler'),
  ('JASONGILLESP', 'Jason Gillespie', 'Australia', 'Bowler'),
  ('IANBOTHAM', 'Ian Botham', 'England', 'All-rounder'),
  ('GRAHAMGOOCH', 'Graham Gooch', 'England', 'Batsman'),
  ('ALECCOOK', 'Alastair Cook', 'England', 'Batsman'),
  ('JAMANDERSON', 'James Anderson', 'England', 'Bowler'),
  ('STUARTBROAD', 'Stuart Broad', 'England', 'Bowler'),
  ('PAULCOLLINGWOOD', 'Paul Collingwood', 'England', 'All-rounder'),
  ('ALLANDONALD', 'Allan Donald', 'South Africa', 'Bowler'),
  ('HANSIECRONJE', 'Hansie Cronje', 'South Africa', 'All-rounder'),
  ('JONTYRHODES', 'Jonty Rhodes', 'South Africa', 'Batsman'),
  ('LANCEKLUSENER', 'Lance Klusener', 'South Africa', 'All-rounder'),
  ('DALESTEYN', 'Dale Steyn', 'South Africa', 'Bowler'),
  ('MLORANI', 'Morne Morkel', 'South Africa', 'Bowler'),
  ('VIVIDRICHARDS', 'Viv Richards', 'West Indies', 'Batsman'),
  ('GORDONGREENI', 'Gordon Greenidge', 'West Indies', 'Batsman'),
  ('DESMONDHAYNE', 'Desmond Haynes', 'West Indies', 'Batsman'),
  ('MICHAELHOLDING', 'Michael Holding', 'West Indies', 'Bowler'),
  ('ANDYROBERTS', 'Andy Roberts', 'West Indies', 'Bowler'),
  ('ARJUNARANATUNGA', 'Arjuna Ranatunga', 'Sri Lanka', 'Batsman'),
  ('ARAVINDADESILVA', 'Aravinda de Silva', 'Sri Lanka', 'Batsman'),
  ('ROMESHKALUWITHARANA', 'Romesh Kaluwitharana', 'Sri Lanka', 'Wicketkeeper'),
  ('TILLAKARATNE', 'Tillakaratne Dilshan', 'Sri Lanka', 'All-rounder'),
  ('RICHARDHADLEE', 'Richard Hadlee', 'New Zealand', 'All-rounder'),
  ('MARTINCROWE', 'Martin Crowe', 'New Zealand', 'Batsman'),
  ('STEPHFLEMING', 'Stephen Fleming', 'New Zealand', 'Batsman'),
  ('CHRISCAIRNS', 'Chris Cairns', 'New Zealand', 'All-rounder'),
  ('ROSST', 'Ross Taylor', 'New Zealand', 'Batsman'),
  ('RASHIDKHANSPIN', 'Rashid Khan', 'Afghanistan', 'Bowler'),
  ('MUJEEBZADRAN', 'Mujeeb Ur Rahman', 'Afghanistan', 'Bowler'),
  ('DAVIDHUSSEY', 'David Hussey', 'Australia', 'Batsman'),
  ('DAMIENMARTYN', 'Damien Martyn', 'Australia', 'Batsman'),
  ('MICHAELBEVAN', 'Michael Bevan', 'Australia', 'Batsman'),
  ('SHANELEE', 'Shane Lee', 'Australia', 'All-rounder'),
  ('IANHARVEY', 'Ian Harvey', 'Australia', 'All-rounder'),
  ('ANDYBICHEL', 'Andy Bichel', 'Australia', 'Bowler'),
  ('NATHANBRACKEN', 'Nathan Bracken', 'Australia', 'Bowler'),
  ('DANCHRISTIAN', 'Dan Christian', 'Australia', 'All-rounder'),
  ('MOISESHENRIQUES', 'Moises Henriques', 'Australia', 'All-rounder'),
  ('STUARTMACGILL', 'Stuart MacGill', 'Australia', 'Bowler'),
  ('TOMMOODY', 'Tom Moody', 'Australia', 'All-rounder'),
  ('SIMONKATICH', 'Simon Katich', 'Australia', 'Batsman'),
  ('PHILHUGHES', 'Phillip Hughes', 'Australia', 'Batsman'),
  ('SHAUNMARSH', 'Shaun Marsh', 'Australia', 'Batsman'),
  ('DEEPAKCHAHAR', 'Deepak Chahar', 'India', 'Bowler'),
  ('TNATARAJAN', 'T Natarajan', 'India', 'Bowler'),
  ('KRUNALPANDYA', 'Krunal Pandya', 'India', 'All-rounder'),
  ('DEEPAKHOODA', 'Deepak Hooda', 'India', 'All-rounder'),
  ('RAHULTEWATIA', 'Rahul Tewatia', 'India', 'All-rounder'),
  ('VENUGOPAL', 'Venugopal Rao', 'India', 'Batsman'),
  ('HEMANGBADANI', 'Hemang Badani', 'India', 'Batsman'),
  ('LAXMIRATAN', 'Laxmi Ratan Shukla', 'India', 'All-rounder'),
  ('DEBASHISH', 'Debashish Mohanty', 'India', 'Bowler'),
  ('ABEYKT', 'Abey Kuruvilla', 'India', 'Bowler'),
  ('NIRANJAN', 'Niranjan Shah', 'India', 'Batsman'),
  ('TOMCURRAN', 'Tom Curran', 'England', 'All-rounder'),
  ('MATTPARKINSON', 'Matt Parkinson', 'England', 'Bowler'),
  ('OWENMORGAN', 'Owen Morgan', 'England', 'Batsman'),
  ('MICHAELVAUGHAN', 'Michael Vaughan', 'England', 'Batsman'),
  ('NASSERHUSSAIN', 'Nasser Hussain', 'England', 'Batsman'),
  ('MARCUSTRESCOTHICK', 'Marcus Trescothick', 'England', 'Batsman'),
  ('ASHLEYGILES', 'Ashley Giles', 'England', 'Bowler'),
  ('STEVEHARMISON', 'Steve Harmison', 'England', 'Bowler'),
  ('MATTHEWHOGGARD', 'Matthew Hoggard', 'England', 'Bowler'),
  ('SIMONCJONES', 'Simon Jones', 'England', 'Bowler'),
  ('DARCYSHORT', 'Darcy Short', 'England', 'Batsman'),
  ('WILLSMEED', 'Will Smeed', 'England', 'Batsman'),
  ('RAMNARESHSARWAN', 'Ramnaresh Sarwan', 'West Indies', 'Batsman'),
  ('CARLHOOPER', 'Carl Hooper', 'West Indies', 'All-rounder'),
  ('RICHIERICHARDSON', 'Richie Richardson', 'West Indies', 'Batsman'),
  ('JEFFDUJON', 'Jeff Dujon', 'West Indies', 'Wicketkeeper'),
  ('ODEANJSMITH', 'Odean Smith', 'West Indies', 'All-rounder'),
  ('USMANQADIR', 'Usman Qadir', 'Pakistan', 'Bowler'),
  ('ABDULQADIR', 'Abdul Qadir', 'Pakistan', 'Bowler'),
  ('SARFARAZN', 'Sarfaraz Nawaz', 'Pakistan', 'Bowler'),
  ('MUDASSAR', 'Mudassar Nazar', 'Pakistan', 'All-rounder'),
  ('ZAHEERABBAS', 'Zaheer Abbas', 'Pakistan', 'Batsman'),
  ('MAJIDKHAN', 'Majid Khan', 'Pakistan', 'Batsman'),
  ('ASIFIQBAL', 'Asif Iqbal', 'Pakistan', 'All-rounder'),
  ('SALEEMM', 'Saleem Malik', 'Pakistan', 'Batsman'),
  ('RAMIZBR', 'Ramiz Raja', 'Pakistan', 'Batsman'),
  ('AAQIBJ', 'Aaqib Javed', 'Pakistan', 'Bowler'),
  ('USMANSH', 'Usman Shinwari', 'Pakistan', 'Bowler'),
  ('KYLEMILLS', 'Kyle Mills', 'New Zealand', 'Bowler'),
  ('NATHANMCCULLUM', 'Nathan McCullum', 'New Zealand', 'All-rounder'),
  ('SCOTTSTYRIS', 'Scott Styris', 'New Zealand', 'All-rounder'),
  ('LOUFINCENT', 'Lou Vincent', 'New Zealand', 'Batsman'),
  ('CRAIGMCMILLAN', 'Craig McMillan', 'New Zealand', 'All-rounder'),
  ('CHRISCAIRNS2', 'Chris Harris', 'New Zealand', 'All-rounder'),
  ('DIONSASH', 'Dion Nash', 'New Zealand', 'All-rounder'),
  ('SHAONEB', 'Shane Bond', 'New Zealand', 'Bowler'),
  ('ADAMPARORE', 'Adam Parore', 'New Zealand', 'Wicketkeeper'),
  ('GLENNTURNER', 'Glenn Turner', 'New Zealand', 'Batsman'),
  ('JOHNNWRIGHT', 'John Wright', 'New Zealand', 'Batsman'),
  ('JREID', 'John Reid', 'New Zealand', 'All-rounder'),
  ('UPULTHARANGA', 'Upul Tharanga', 'Sri Lanka', 'Batsman'),
  ('ROSHANM', 'Roshan Mahanama', 'Sri Lanka', 'Batsman'),
  ('ASANKAGURUSINGHE', 'Asanka Gurusinha', 'Sri Lanka', 'Batsman'),
  ('HASHAN', 'Hashan Tillakaratne', 'Sri Lanka', 'Batsman'),
  ('PRAMODYADG', 'Pramodya Wickramasinghe', 'Sri Lanka', 'Bowler'),
  ('SURANGA', 'Suranga Lakmal', 'Sri Lanka', 'Bowler'),
  ('AJANTHAM', 'Ajantha Mendis', 'Sri Lanka', 'Bowler'),
  ('JEEVAN', 'Jeevan Mendis', 'Sri Lanka', 'All-rounder'),
  ('NIROSHAN', 'Niroshan Dickwella', 'Sri Lanka', 'Wicketkeeper'),
  ('LITTON', 'Litton Das', 'Bangladesh', 'Wicketkeeper'),
  ('KHALEDSM', 'Khaled Mashud', 'Bangladesh', 'Wicketkeeper'),
  ('MOHAMMADRAFTQ', 'Mohammad Rafique', 'Bangladesh', 'All-rounder'),
  ('LITONKD', 'Liton Kumer Das', 'Bangladesh', 'Batsman'),
  ('CLIVERICE', 'Clive Rice', 'South Africa', 'All-rounder'),
  ('JIMMYCOOK', 'Jimmy Cook', 'South Africa', 'Batsman'),
  ('KEPLER', 'Kepler Wessels', 'South Africa', 'Batsman'),
  ('ADRIANKUIPER', 'Adrian Kuiper', 'South Africa', 'All-rounder'),
  ('PETERK', 'Peter Kirsten', 'South Africa', 'Batsman'),
  ('GARYKIR', 'Gary Kirsten', 'South Africa', 'Batsman'),
  ('DARYLLCULLINAN', 'Daryll Cullinan', 'South Africa', 'Batsman'),
  ('BRIAN', 'Brian McMillan', 'South Africa', 'All-rounder'),
  ('DAVIDRIC', 'Dave Richardson', 'South Africa', 'Wicketkeeper'),
  ('NEILM', 'Neil McKenzie', 'South Africa', 'Batsman'),
  ('BOETAD', 'Boeta Dippenaar', 'South Africa', 'Batsman'),
  ('ANDRENETRUMPER', 'Andrew Hall', 'South Africa', 'All-rounder'),
  ('JUSTINKEMPT', 'Justin Kemp', 'South Africa', 'All-rounder'),
  ('ROBBIE', 'Robbie Peterson', 'South Africa', 'Bowler'),
  ('JOHANNBOTHA', 'Johan Botha', 'South Africa', 'All-rounder'),
  ('RYANMCLA', 'Ryan McLaren', 'South Africa', 'All-rounder'),
  ('DAVIDHTON', 'Dave Houghton', 'Zimbabwe', 'Batsman'),
  ('EDDOMBRANDT', 'Eddo Brandes', 'Zimbabwe', 'Bowler'),
  ('PAULSTRANG', 'Paul Strang', 'Zimbabwe', 'Bowler'),
  ('GARYWH', 'Gary Brent', 'Zimbabwe', 'Batsman'),
  ('EDJOYC', 'Ed Joyce', 'Ireland', 'Batsman'),
  ('NIOBRYEN', 'Niall O''Brien', 'Ireland', 'Wicketkeeper'),
  ('JOHNYMOONEY', 'John Mooney', 'Ireland', 'All-rounder'),
  ('BOYDRANKIN', 'Boyd Rankin', 'Ireland', 'Bowler'),
  ('ANDYBALBI', 'Andy Balbirnie', 'Ireland', 'Batsman'),
  ('AJITAGARKAR', 'Ajit Agarkar', 'India', 'Bowler'),
  ('PRAGYANOJHA', 'Pragyan Ojha', 'India', 'Bowler'),
  ('SREESANTH', 'S Sreesanth', 'India', 'Bowler'),
  ('SADAGOPPAN', 'Sadagoppan Ramesh', 'India', 'Batsman'),
  ('VENKATESHI', 'Venkatesh Iyer', 'India', 'All-rounder'),
  ('ABHISHEKSHARMA', 'Abhishek Sharma', 'India', 'All-rounder'),
  ('MAYANKYADAV', 'Mayank Yadav', 'India', 'Bowler'),
  ('SANDEEPWARRIER', 'Sandeep Warrier', 'India', 'Bowler'),
  ('JAYDEVUNADKAT', 'Jaydev Unadkat', 'India', 'Bowler'),
  ('ANUJRAWAT', 'Anuj Rawat', 'India', 'Wicketkeeper'),
  ('DHRUVSHOREY', 'Dhruv Shorey', 'India', 'Batsman'),
  ('RAJATPATIDAR', 'Rajat Patidar', 'India', 'Batsman'),
  ('FAWADALAM', 'Fawad Alam', 'Pakistan', 'Batsman'),
  ('USAMAMIR', 'Usama Mir', 'Pakistan', 'Bowler'),
  ('ZAMAN', 'Zaman Khan', 'Pakistan', 'Bowler'),
  ('IRFANKHAN', 'Irfan Khan', 'Pakistan', 'Batsman'),
  ('NATHANELLIS', 'Nathan Ellis', 'Australia', 'Bowler'),
  ('JHYERICHARDSON', 'Jhye Richardson', 'Australia', 'Bowler'),
  ('KANERICHARD', 'Kane Richardson', 'Australia', 'Bowler'),
  ('ANDREWTYE', 'Andrew Tye', 'Australia', 'Bowler'),
  ('BILLYSTANLAKE', 'Billy Stanlake', 'Australia', 'Bowler'),
  ('DEVONSM', 'Devon Smith', 'West Indies', 'Batsman'),
  ('KIERANPOW', 'Kieran Powell', 'West Indies', 'Batsman'),
  ('YANNICKCARN', 'Yannic Cariah', 'West Indies', 'Bowler'),
  ('KEMORPAUL', 'Keemo Paul', 'West Indies', 'All-rounder'),
  ('TOMBURWELL', 'Tom Banton', 'England', 'Batsman'),
  ('SAMHAIN', 'Sam Hain', 'England', 'Batsman'),
  ('TOMAH', 'Tom Abell', 'England', 'All-rounder'),
  ('OLLIEROB', 'Ollie Robinson', 'England', 'Bowler'),
  ('CHETESH', 'Saqib Mahmood', 'England', 'Bowler'),
  ('JAMISHR', 'Jamie Overton', 'England', 'Bowler'),
  ('MATTPO', 'Matt Potts', 'England', 'Bowler'),
  ('BRIANBRYDON', 'Brydon Carse', 'England', 'Bowler'),
  ('RYANTENDOBTE', 'Ryan ten Doeschate', 'Netherlands', 'All-rounder'),
  ('WESSELBARENDREGT', 'Wesley Barresi', 'Netherlands', 'Batsman'),
  ('TIMBVL', 'Tim van der Gugten', 'Netherlands', 'Bowler'),
  ('TOBIASVISK', 'Tobias Visee', 'Netherlands', 'Batsman'),
  ('SAQIBZ', 'Saqib Zulfiqar', 'Netherlands', 'Batsman'),
  ('JOSHD', 'Josh Davey', 'Scotland', 'Bowler'),
  ('MICHAELJONES', 'Michael Jones', 'Scotland', 'Batsman'),
  ('BRANDONMC', 'Brandon McMullen', 'Scotland', 'All-rounder'),
  ('JANFRYLINCK', 'Jan Frylinck', 'Namibia', 'All-rounder'),
  ('MICHIELT', 'Michiel du Preez', 'Namibia', 'Batsman'),
  ('TANGATANG', 'Tangeni Lungameni', 'Namibia', 'Bowler'),
  ('JATINDERS', 'Jatinder Singh', 'Oman', 'Batsman'),
  ('MOHAMMEDNADE', 'Mohammad Nadeem', 'Oman', 'Batsman'),
  ('NASSEMKH', 'Naseem Khushi', 'Oman', 'Wicketkeeper');