-- ============================================
-- PLAYERS DATA IMPORT
-- ============================================

INSERT INTO players (id, full_name, country, role) VALUES
  ('AARONJONES', 'Aaron Jones', 'United States of America', 'All-rounder'),
  ('AASIFSHEIKH', 'Aasif Sheikh', 'Nepal', 'Wicketkeeper'),
  ('ABALBIRNIE', 'Andrew Balbirnie', 'Ireland', 'Batsman'),
  ('ABBASAFRIDI', 'Abbas Afridi', 'Pakistan', 'Bowler'),
  ('ABDEVILLIERS', 'AB de Villiers', 'South Africa', 'Batsman'),
  ('ABOHARA', 'Anil Bohara', 'Nepal', 'Bowler'),
  ('ACAGAR', 'Ashton Agar', 'Australia', 'All-rounder'),
  ('ACEVANS', 'Alasdair Evans', 'Scotland', 'Bowler'),
  ('ADHALES', 'Alex Hales', 'England', 'Batsman'),
  ('ADMATHEWS', 'Angelo Mathews', 'Sri Lanka', 'All-rounder'),
  ('ADRUSSELL', 'Andre Russell', 'West Indies', 'All-rounder'),
  ('ADSFLETCHER', 'Andre Fletcher', 'West Indies', 'Wicketkeeper'),
  ('AFIFHOSSAIN', 'Afif Hossain', 'Bangladesh', 'All-rounder'),
  ('AFMILNE', 'Adam Milne', 'New Zealand', 'Bowler'),
  ('AGSGOUS', 'Andries Gous', 'United States of America', 'Wicketkeeper'),
  ('AHMEDSHEHZAD', 'Ahmed Shehzad', 'Pakistan', 'Batsman'),
  ('AJFINCH', 'Aaron Finch', 'Australia', 'Batsman'),
  ('AJHOSEIN', 'Akeal Hosein', 'West Indies', 'Bowler'),
  ('AKMARKRAM', 'Aiden Markram', 'South Africa', 'Batsman'),
  ('AKSAH', 'Aakash Sah', 'Nepal', 'Batsman'),
  ('ALAMINHOSSAIN', 'Al-Amin Hossain', 'Bangladesh', 'Bowler'),
  ('ALIKHAN', 'Ali Khan', 'United States of America', 'Bowler'),
  ('AMISHRA', 'Amit Mishra', 'India', 'Bowler'),
  ('AMPHANGISO', 'Aaron Phangiso', 'South Africa', 'Bowler'),
  ('AMRAHANE', 'Ajinkya Rahane', 'India', 'Batsman'),
  ('ANAMULHAQUE', 'Anamul Haque', 'Bangladesh', 'Wicketkeeper'),
  ('ANEHRA', 'Ashish Nehra', 'India', 'Bowler'),
  ('ANORTJE', 'Anrich Nortje', 'South Africa', 'Bowler'),
  ('AQIBILYAS', 'Aqib Ilyas', 'Oman', 'All-rounder'),
  ('ARPATEL', 'Axar Patel', 'India', 'All-rounder'),
  ('ARSHDEEPSINGH', 'Arshdeep Singh', 'India', 'Bowler'),
  ('ASIFALI', 'Asif Ali', 'Pakistan', 'Batsman'),
  ('ASJOSEPH', 'Alzarri Joseph', 'West Indies', 'Bowler'),
  ('ATNIDAMANURU', 'Teja Nidamanuru', 'Netherlands', 'Batsman'),
  ('AURASHID', 'Adil Rashid', 'England', 'Bowler'),
  ('AYANKHAN', 'Ayan Khan', 'Oman', 'All-rounder'),
  ('AZAMPA', 'Adam Zampa', 'Australia', 'Bowler'),
  ('BABARAZAM', 'Babar Azam', 'Pakistan', 'Batsman'),
  ('BAKING', 'Brandon King', 'West Indies', 'Batsman'),
  ('BASTOKES', 'Ben Stokes', 'England', 'All-rounder'),
  ('BAWMENDIS', 'Kusal Mendis', 'Sri Lanka', 'Wicketkeeper'),
  ('BDGLOVER', 'Bas de Leede', 'Netherlands', 'All-rounder'),
  ('BEHENDRICKS', 'Beuran Hendricks', 'South Africa', 'Bowler'),
  ('BFWDELEEDE', 'Bas de Leede', 'Netherlands', 'All-rounder'),
  ('BILALKHAN', 'Bilal Khan', 'Oman', 'Bowler'),
  ('BJHADDIN', 'Brad Haddin', 'Australia', 'Wicketkeeper'),
  ('BJHODGE', 'Brad Hodge', 'Australia', 'Batsman'),
  ('BJMCCARTHY', 'Barry McCarthy', 'Ireland', 'Bowler'),
  ('BKGMENDIS', 'Kusal Mendis', 'Sri Lanka', 'Wicketkeeper'),
  ('BKUMAR', 'Bhuvneshwar Kumar', 'India', 'Bowler'),
  ('BMSCHOLTZ', 'Bernard Scholtz', 'Namibia', 'Bowler'),
  ('BMUZARABANI', 'Blessing Muzarabani', 'Zimbabwe', 'Bowler'),
  ('BSHIKONGO', 'Ben Shikongo', 'Namibia', 'Bowler'),
  ('BTJWHEAL', 'Brad Wheal', 'Scotland', 'Bowler'),
  ('BWHITE', 'Barry White', 'Ireland', 'Bowler'),
  ('CAKRAJITHA', 'Kasun Rajitha', 'Sri Lanka', 'Bowler'),
  ('CBRLSKUMARA', 'Lahiru Kumara', 'Sri Lanka', 'Bowler'),
  ('CCAMPHER', 'Curtis Campher', 'Ireland', 'All-rounder'),
  ('CGWILLIAMS', 'Craig Williams', 'Namibia', 'Batsman'),
  ('CHGAYLE', 'Chris Gayle', 'West Indies', 'Batsman'),
  ('CHMORRIS', 'Chris Morris', 'South Africa', 'All-rounder'),
  ('CJANDERSON', 'Corey Anderson', 'United States of America', 'All-rounder'),
  ('CJJORDAN', 'Chris Jordan', 'England', 'Bowler'),
  ('CKARUNARATNE', 'Charith Asalanka', 'Sri Lanka', 'Batsman'),
  ('CKKAPUGEDERA', 'Chamara Kapugedera', 'Sri Lanka', 'Batsman'),
  ('CLWHITE', 'Cameron White', 'Australia', 'All-rounder'),
  ('CMUNRO', 'Colin Munro', 'New Zealand', 'Batsman'),
  ('CNACKERMANN', 'Colin Ackermann', 'Netherlands', 'All-rounder'),
  ('CNGREAVES', 'Chris Greaves', 'Scotland', 'All-rounder'),
  ('CRBRATHWAITE', 'Carlos Brathwaite', 'West Indies', 'All-rounder'),
  ('CRERVINE', 'Craig Ervine', 'Zimbabwe', 'Batsman'),
  ('CRWOAKES', 'Chris Woakes', 'England', 'All-rounder'),
  ('CSMACLEOD', 'Calum MacLeod', 'Scotland', 'Batsman'),
  ('CVVARUN', 'Varun Chakravarthy', 'India', 'Bowler'),
  ('DAMILLER', 'David Miller', 'South Africa', 'Batsman'),
  ('DAWARNER', 'David Warner', 'Australia', 'Batsman'),
  ('DEBOLLINGER', 'Doug Bollinger', 'Australia', 'Bowler'),
  ('DEBUDGE', 'David Budge', 'Scotland', 'Bowler'),
  ('DJBRAVO', 'Dwayne Bravo', 'West Indies', 'All-rounder'),
  ('DJGSAMMY', 'Darren Sammy', 'West Indies', 'All-rounder'),
  ('DJMALAN', 'Dawid Malan', 'England', 'Batsman'),
  ('DJMITCHELL', 'Daryl Mitchell', 'New Zealand', 'All-rounder'),
  ('DJWILLEY', 'David Willey', 'England', 'All-rounder'),
  ('DMDESILVA', 'Dhananjaya de Silva', 'Sri Lanka', 'All-rounder'),
  ('DPCONWAY', 'Devon Conway', 'New Zealand', 'Batsman'),
  ('DPMDJAYAWARDENE', 'Mahela Jayawardene', 'Sri Lanka', 'Batsman'),
  ('DPRETORIUS', 'Dwaine Pretorius', 'South Africa', 'All-rounder'),
  ('DRAMDIN', 'Denesh Ramdin', 'West Indies', 'Wicketkeeper'),
  ('DRSMITH', 'Dwayne Smith', 'West Indies', 'All-rounder'),
  ('DSAIREE', 'Dipendra Airee', 'Nepal', 'All-rounder'),
  ('DWIESE', 'David Wiese', 'Namibia', 'All-rounder'),
  ('DWSTEYN', 'Dale Steyn', 'South Africa', 'Bowler'),
  ('EBADATHOSSAIN', 'Ebadot Hossain', 'Bangladesh', 'Bowler'),
  ('EJGMORGAN', 'Eoin Morgan', 'England', 'Batsman'),
  ('ELEWIS', 'Evin Lewis', 'West Indies', 'Batsman'),
  ('FAKHARZAMAN', 'Fakhar Zaman', 'Pakistan', 'Batsman'),
  ('FAYYAZBUTT', 'Fayyaz Butt', 'Oman', 'Bowler'),
  ('FDUPLESSIS', 'Faf du Plessis', 'South Africa', 'Batsman'),
  ('FHALLEN', 'Finn Allen', 'New Zealand', 'Batsman'),
  ('FJKLAASSEN', 'Fred Klaassen', 'Netherlands', 'Bowler'),
  ('GDELLIOTT', 'Grant Elliott', 'New Zealand', 'All-rounder'),
  ('GDPHILLIPS', 'Glenn Phillips', 'New Zealand', 'Batsman'),
  ('GHDOCKRELL', 'George Dockrell', 'Ireland', 'Bowler'),
  ('GJBAILEY', 'George Bailey', 'Australia', 'Batsman'),
  ('GJDELANY', 'Gareth Delany', 'Ireland', 'All-rounder'),
  ('GJMAXWELL', 'Glenn Maxwell', 'Australia', 'All-rounder'),
  ('GMOTIE', 'Gudakesh Motie', 'West Indies', 'Bowler'),
  ('GULSANJHA', 'Gulsan Jha', 'Nepal', 'Bowler'),
  ('HAIDERALI', 'Haider Ali', 'Pakistan', 'Batsman'),
  ('HAMZATAHIR', 'Hamza Tahir', 'Scotland', 'Bowler'),
  ('HARISRAUF', 'Haris Rauf', 'Pakistan', 'Bowler'),
  ('HARMEETSINGH', 'Harmeet Singh', 'United States of America', 'Bowler'),
  ('HASANALI', 'Hasan Ali', 'Pakistan', 'Bowler'),
  ('HASANMAHMUD', 'Hasan Mahmud', 'Bangladesh', 'Bowler'),
  ('HCBROOK', 'Harry Brook', 'England', 'Batsman'),
  ('HDRLTHIRIMANNE', 'Lahiru Thirimanne', 'Sri Lanka', 'Batsman'),
  ('HEVANDERDUSSEN', 'Rassie van der Dussen', 'South Africa', 'Batsman'),
  ('HGMUNSEY', 'George Munsey', 'Scotland', 'Batsman'),
  ('HHPANDYA', 'Hardik Pandya', 'India', 'All-rounder'),
  ('HKLAASEN', 'Heinrich Klaasen', 'South Africa', 'Wicketkeeper'),
  ('HMAMLA', 'Hashim Amla', 'South Africa', 'Batsman'),
  ('HMRKBHERATH', 'Rangana Herath', 'Sri Lanka', 'Bowler'),
  ('HRWALSH', 'Hayden Walsh Jr', 'West Indies', 'Bowler'),
  ('HTTECTOR', 'Harry Tector', 'Ireland', 'Batsman'),
  ('IFTIKHARAHMED', 'Iftikhar Ahmed', 'Pakistan', 'All-rounder'),
  ('IMADWASIM', 'Imad Wasim', 'Pakistan', 'All-rounder'),
  ('IMRANTAHIR', 'Imran Tahir', 'South Africa', 'Bowler'),
  ('ISSODHI', 'Ish Sodhi', 'New Zealand', 'Bowler'),
  ('JAKERALI', 'Jaker Ali', 'Bangladesh', 'Wicketkeeper'),
  ('JAMORKEL', 'Albie Morkel', 'South Africa', 'All-rounder'),
  ('JASDEEPSINGH', 'Jasdeep Singh', 'United States of America', 'Bowler'),
  ('JCARCHER', 'Jofra Archer', 'England', 'Bowler'),
  ('JCBUTTLER', 'Jos Buttler', 'England', 'Wicketkeeper'),
  ('JCHARLES', 'Johnson Charles', 'West Indies', 'Wicketkeeper'),
  ('JCTREDWELL', 'James Tredwell', 'England', 'Bowler'),
  ('JDFVANDERSAY', 'Jeffrey Vandersay', 'Sri Lanka', 'Bowler'),
  ('JDSNEESHAM', 'Jimmy Neesham', 'New Zealand', 'All-rounder'),
  ('JEROOT', 'Joe Root', 'England', 'Batsman'),
  ('JETAYLOR', 'Jerome Taylor', 'West Indies', 'Bowler'),
  ('JJBUMRAH', 'Jasprit Bumrah', 'India', 'Bowler'),
  ('JJROY', 'Jason Roy', 'England', 'Batsman'),
  ('JJSMIT', 'JJ Smit', 'Namibia', 'All-rounder'),
  ('JLITTLE', 'Josh Little', 'Ireland', 'Bowler'),
  ('JMBAIRSTOW', 'Jonny Bairstow', 'England', 'Wicketkeeper'),
  ('JMMUIRHEAD', 'James Muirhead', 'Australia', 'Bowler'),
  ('JNFRYLINCK', 'JJ Frylinck', 'Namibia', 'All-rounder'),
  ('JNLOFTIEEATON', 'Jan Loftie-Eaton', 'Namibia', 'All-rounder'),
  ('JPDUMINY', 'JP Duminy', 'South Africa', 'All-rounder'),
  ('JPFAULKNER', 'James Faulkner', 'Australia', 'All-rounder'),
  ('JPKOTZE', 'JJ Kotze', 'Namibia', 'Batsman'),
  ('JRHAZLEWOOD', 'Josh Hazlewood', 'Australia', 'Bowler'),
  ('JTBRASSELL', 'Ruben Trumpelmann', 'Namibia', 'Bowler'),
  ('JWDERNBACH', 'Jade Dernbach', 'England', 'Bowler'),
  ('KALEEMULLAH', 'Kaleemullah', 'Oman', 'Bowler'),
  ('KAMAHARAJ', 'Keshav Maharaj', 'South Africa', 'Bowler'),
  ('KAMRANAKMAL', 'Kamran Akmal', 'Pakistan', 'Wicketkeeper'),
  ('KAPOLLARD', 'Kieron Pollard', 'West Indies', 'All-rounder'),
  ('KARANKC', 'Karan KC', 'Nepal', 'All-rounder'),
  ('KBHURTEL', 'Kushal Bhurtel', 'Nepal', 'Batsman'),
  ('KCSANGAKKARA', 'Kumar Sangakkara', 'Sri Lanka', 'Wicketkeeper'),
  ('KDKARTHIK', 'Dinesh Karthik', 'India', 'Wicketkeeper'),
  ('KHALIDKAIL', 'Khalid Kail', 'Oman', 'Batsman'),
  ('KHPRAJAPATI', 'Kashyap Prajapati', 'Oman', 'Batsman'),
  ('KICASALANKA', 'Charith Asalanka', 'Sri Lanka', 'Batsman'),
  ('KJABBOTT', 'Kyle Abbott', 'South Africa', 'Bowler'),
  ('KJCOETZER', 'Kyle Coetzer', 'Scotland', 'Batsman'),
  ('KLRAHUL', 'KL Rahul', 'India', 'Wicketkeeper'),
  ('KMDNKULASEKARA', 'Nuwan Kulasekara', 'Sri Lanka', 'Bowler'),
  ('KRABADA', 'Kagiso Rabada', 'South Africa', 'Bowler'),
  ('KRMAYERS', 'Kyle Mayers', 'West Indies', 'All-rounder'),
  ('KSANTOKIE', 'Krishmar Santokie', 'West Indies', 'Bowler'),
  ('KSWILLIAMSON', 'Kane Williamson', 'New Zealand', 'Batsman'),
  ('KULDEEPYADAV', 'Kuldeep Yadav', 'India', 'Bowler'),
  ('KUSHALMALLA', 'Kushal Malla', 'Nepal', 'All-rounder'),
  ('LDCHANDIMAL', 'Dinesh Chandimal', 'Sri Lanka', 'Wicketkeeper'),
  ('LEPLUNKETT', 'Liam Plunkett', 'England', 'Bowler'),
  ('LHFERGUSON', 'Lockie Ferguson', 'New Zealand', 'Bowler'),
  ('LITONDAS', 'Liton Das', 'Bangladesh', 'Wicketkeeper'),
  ('LMPSIMMONS', 'Lendl Simmons', 'West Indies', 'Batsman'),
  ('LNGIDI', 'Lungi Ngidi', 'South Africa', 'Bowler'),
  ('LRONCHI', 'Luke Ronchi', 'New Zealand', 'Wicketkeeper'),
  ('LRPLTAYLOR', 'Ross Taylor', 'New Zealand', 'Batsman'),
  ('LSLIVINGSTONE', 'Liam Livingstone', 'England', 'All-rounder'),
  ('LTUCKER', 'Lorcan Tucker', 'Ireland', 'Wicketkeeper'),
  ('LVVANBEEK', 'Logan van Beek', 'Netherlands', 'All-rounder'),
  ('MAHEDIHASAN', 'Mahedi Hasan', 'Bangladesh', 'All-rounder'),
  ('MAHMUDULLAH', 'Mahmudullah', 'Bangladesh', 'All-rounder'),
  ('MALEASK', 'Michael Leask', 'Scotland', 'All-rounder'),
  ('MASHRAFEMORTAZA', 'Mashrafe Mortaza', 'Bangladesh', 'Bowler'),
  ('MASTARC', 'Mitchell Starc', 'Australia', 'Bowler'),
  ('MAWOOD', 'Mark Wood', 'England', 'Bowler'),
  ('MDKJPERERA', 'Kusal Perera', 'Sri Lanka', 'Wicketkeeper'),
  ('MDSHANAKA', 'Dasun Shanaka', 'Sri Lanka', 'All-rounder'),
  ('MEHRANKHAN', 'Mehran Khan', 'Oman', 'Bowler'),
  ('MGERASMUS', 'Gerhard Erasmus', 'Namibia', 'All-rounder'),
  ('MHCROSS', 'Matthew Cross', 'Scotland', 'Wicketkeeper'),
  ('MILINDKUMAR', 'Milind Kumar', 'United States of America', 'Batsman'),
  ('MJANSEN', 'Marco Jansen', 'South Africa', 'All-rounder'),
  ('MJGUPTILL', 'Martin Guptill', 'New Zealand', 'Batsman'),
  ('MJLUMB', 'Michael Lumb', 'England', 'Batsman'),
  ('MJMCCLENAGHAN', 'Mitchell McClenaghan', 'New Zealand', 'Bowler'),
  ('MJSANTNER', 'Mitchell Santner', 'New Zealand', 'All-rounder'),
  ('MKPANDEY', 'Manish Pandey', 'India', 'Batsman'),
  ('MLEVITT', 'Michael Levitt', 'Netherlands', 'Bowler'),
  ('MMALI', 'Moeen Ali', 'England', 'All-rounder'),
  ('MMSHARMA', 'Mohit Sharma', 'India', 'Bowler'),
  ('MNSAMUELS', 'Marlon Samuels', 'West Indies', 'All-rounder'),
  ('MOHAMMADAMIR', 'Mohammad Amir', 'Pakistan', 'Bowler'),
  ('MOHAMMADHAFEEZ', 'Mohammad Hafeez', 'Pakistan', 'All-rounder'),
  ('MOHAMMADHARIS', 'Mohammad Haris', 'Pakistan', 'Wicketkeeper'),
  ('MOHAMMADIRFAN', 'Mohammad Irfan', 'Pakistan', 'Bowler'),
  ('MOHAMMADMITHUN', 'Mohammad Mithun', 'Bangladesh', 'Batsman'),
  ('MOHAMMADNAIM', 'Mohammad Naim', 'Bangladesh', 'Batsman'),
  ('MOHAMMADNAWAZ', 'Mohammad Nawaz', 'Pakistan', 'All-rounder'),
  ('MOHAMMADRIZWAN', 'Mohammad Rizwan', 'Pakistan', 'Wicketkeeper'),
  ('MOHAMMADSAMI', 'Mohammad Sami', 'Pakistan', 'Bowler'),
  ('MOHAMMADWASIM', 'Mohammad Wasim Jr', 'Pakistan', 'All-rounder'),
  ('MOHAMMEDSHAMI', 'Mohammed Shami', 'India', 'Bowler'),
  ('MOHAMMEDSIRAJ', 'Mohammed Siraj', 'India', 'Bowler'),
  ('MOSADDEKHOSSAIN', 'Mosaddek Hossain', 'Bangladesh', 'All-rounder'),
  ('MPATHIRANA', 'Matheesha Pathirana', 'Sri Lanka', 'Bowler'),
  ('MPODOWD', 'Max O''Dowd', 'Netherlands', 'Batsman'),
  ('MPSTOINIS', 'Marcus Stoinis', 'Australia', 'All-rounder'),
  ('MRADAIR', 'Mark Adair', 'Ireland', 'All-rounder'),
  ('MRJWATT', 'Mark Watt', 'Scotland', 'Bowler'),
  ('MRMARSH', 'Mitch Marsh', 'Australia', 'All-rounder'),
  ('MSDHONI', 'MS Dhoni', 'India', 'Wicketkeeper'),
  ('MSWADE', 'Matthew Wade', 'Australia', 'Wicketkeeper'),
  ('MTHEEKSHANA', 'Maheesh Theekshana', 'Sri Lanka', 'Bowler'),
  ('MUSHFIQURRAHIM', 'Mushfiqur Rahim', 'Bangladesh', 'Wicketkeeper'),
  ('MUSTAFIZURRAHMAN', 'Mustafizur Rahman', 'Bangladesh', 'Bowler'),
  ('MVANLINGEN', 'Michael van Lingen', 'Namibia', 'Batsman'),
  ('NASEEMSHAH', 'Naseem Shah', 'Pakistan', 'Bowler'),
  ('NASIRHOSSAIN', 'Nasir Hossain', 'Bangladesh', 'All-rounder'),
  ('NASUMAHMED', 'Nasum Ahmed', 'Bangladesh', 'Bowler'),
  ('NAZMULHOSSAINSHANTO', 'Najmul Hossain Shanto', 'Bangladesh', 'Batsman'),
  ('NDAVIN', 'Nicol Loftie-Eaton', 'Namibia', 'Batsman'),
  ('NLTCPERERA', 'Thisara Perera', 'Sri Lanka', 'All-rounder'),
  ('NMCOULTERNILE', 'Nathan Coulter-Nile', 'Australia', 'Bowler'),
  ('NPKENJIGE', 'Nosthush Kenjige', 'United States of America', 'Bowler'),
  ('NPOORAN', 'Nicholas Pooran', 'West Indies', 'Wicketkeeper'),
  ('NRKUMAR', 'Nitish Kumar', 'United States of America', 'All-rounder'),
  ('NTHUSHARA', 'Nuwan Thushara', 'Sri Lanka', 'Bowler'),
  ('NURULHASAN', 'Nurul Hasan', 'Bangladesh', 'Wicketkeeper'),
  ('OCMCCOY', 'Obed McCoy', 'West Indies', 'Bowler'),
  ('OEGBAARTMAN', 'Ottneil Baartman', 'South Africa', 'Bowler'),
  ('PAVANMEEKEREN', 'Paul van Meekeren', 'Netherlands', 'Bowler'),
  ('PBBRAJAPAKSA', 'Bhanuka Rajapaksa', 'Sri Lanka', 'Batsman'),
  ('PDSALT', 'Phil Salt', 'England', 'Wicketkeeper'),
  ('PHKDMENDIS', 'Kusal Mendis', 'Sri Lanka', 'Wicketkeeper'),
  ('PJCUMMINS', 'Pat Cummins', 'Australia', 'Bowler'),
  ('PMNEVILL', 'Peter Nevill', 'Australia', 'Wicketkeeper'),
  ('PNISSANKA', 'Pathum Nissanka', 'Sri Lanka', 'Batsman'),
  ('PRSTIRLING', 'Paul Stirling', 'Ireland', 'Batsman'),
  ('PSATHAVALE', 'Pratik Athavale', 'Oman', 'Wicketkeeper'),
  ('PVDCHAMEERA', 'Dushmantha Chameera', 'Sri Lanka', 'Bowler'),
  ('PWHDESILVA', 'Wanindu Hasaranga', 'Sri Lanka', 'All-rounder'),
  ('QDEKOCK', 'Quinton de Kock', 'South Africa', 'Wicketkeeper'),
  ('RAJADEJA', 'Ravindra Jadeja', 'India', 'All-rounder'),
  ('RASHWIN', 'Ravichandran Ashwin', 'India', 'All-rounder'),
  ('RDBERRINGTON', 'Richie Berrington', 'Scotland', 'All-rounder'),
  ('RDCHAHAR', 'Rahul Chahar', 'India', 'Bowler'),
  ('REVANDERMERWE', 'Roelof van der Merwe', 'Netherlands', 'All-rounder'),
  ('RGSHARMA', 'Rohit Sharma', 'India', 'Batsman'),
  ('RISHADHOSSAIN', 'Rishad Hossain', 'Bangladesh', 'Bowler'),
  ('RJWTOPLEY', 'Reece Topley', 'England', 'Bowler'),
  ('RKPAUDEL', 'Rohit Paudel', 'Nepal', 'Batsman'),
  ('RLCHASE', 'Roston Chase', 'West Indies', 'All-rounder'),
  ('RNGARAVA', 'Richard Ngarava', 'Zimbabwe', 'Bowler'),
  ('RPBURL', 'Ryan Burl', 'Zimbabwe', 'All-rounder'),
  ('RPOWELL', 'Rovman Powell', 'West Indies', 'Batsman'),
  ('RRAMPAUL', 'Ravi Rampaul', 'West Indies', 'Bowler'),
  ('RRHENDRICKS', 'Reeza Hendricks', 'South Africa', 'Batsman'),
  ('RRPANT', 'Rishabh Pant', 'India', 'Wicketkeeper'),
  ('RRROSSOUW', 'Rilee Rossouw', 'South Africa', 'Batsman'),
  ('RSBOPARA', 'Ravi Bopara', 'England', 'All-rounder'),
  ('RSHEPHERD', 'Romario Shepherd', 'West Indies', 'All-rounder'),
  ('RTRUMPELMANN', 'Ruben Trumpelmann', 'Namibia', 'Bowler'),
  ('RWCHAKABVA', 'Regis Chakabva', 'Zimbabwe', 'Wicketkeeper'),
  ('SABBIRRAHMAN', 'Sabbir Rahman', 'Bangladesh', 'Batsman'),
  ('SAEDWARDS', 'Scott Edwards', 'Netherlands', 'Wicketkeeper'),
  ('SAEEDAJMAL', 'Saeed Ajmal', 'Pakistan', 'Bowler'),
  ('SAENGELBRECHT', 'Sybrand Engelbrecht', 'Netherlands', 'Batsman'),
  ('SAIMAYUB', 'Saim Ayub', 'Pakistan', 'Batsman'),
  ('SARFRAZAHMED', 'Sarfaraz Ahmed', 'Pakistan', 'Wicketkeeper'),
  ('SAYADAV', 'Suryakumar Yadav', 'India', 'Batsman'),
  ('SBADREE', 'Samuel Badree', 'West Indies', 'Bowler'),
  ('SCJBROAD', 'Stuart Broad', 'England', 'Bowler'),
  ('SCVANSCHALKWYK', 'Saurabh Netravalkar', 'United States of America', 'Bowler'),
  ('SCWILLIAMS', 'Sean Williams', 'Zimbabwe', 'All-rounder'),
  ('SDHAWAN', 'Shikhar Dhawan', 'India', 'Batsman'),
  ('SDHOPE', 'Shai Hope', 'West Indies', 'Wicketkeeper'),
  ('SDUBE', 'Shivam Dube', 'India', 'All-rounder'),
  ('SERUTHERFORD', 'Sherfane Rutherford', 'West Indies', 'Batsman'),
  ('SHADABKHAN', 'Shadab Khan', 'Pakistan', 'All-rounder'),
  ('SHAHEENSHAHAFRIDI', 'Shaheen Shah Afridi', 'Pakistan', 'Bowler'),
  ('SHAHIDAFRIDI', 'Shahid Afridi', 'Pakistan', 'All-rounder'),
  ('SHAKIBALHASAN', 'Shakib Al Hasan', 'Bangladesh', 'All-rounder'),
  ('SHAMIMHOSSAIN', 'Shamim Hossain', 'Bangladesh', 'All-rounder'),
  ('SHAMSURRAHMAN', 'Shamsur Rahman', 'Bangladesh', 'Batsman'),
  ('SHANMASOOD', 'Shan Masood', 'Pakistan', 'Batsman'),
  ('SHARIZAHMAD', 'Shariz Ahmad', 'Netherlands', 'Bowler'),
  ('SHARJEELKHAN', 'Sharjeel Khan', 'Pakistan', 'Batsman'),
  ('SHAYANJAHANGIR', 'Shayan Jahangir', 'United States of America', 'Batsman'),
  ('SHOAIBKHAN', 'Shoaib Khan', 'Oman', 'Batsman'),
  ('SHOAIBMALIK', 'Shoaib Malik', 'Pakistan', 'All-rounder'),
  ('SHORIFULISLAM', 'Shoriful Islam', 'Bangladesh', 'Bowler'),
  ('SHUVAGATAHOM', 'Shuvagata Hom', 'Bangladesh', 'All-rounder'),
  ('SIKANDARRAZA', 'Sikandar Raza', 'Zimbabwe', 'All-rounder'),
  ('SJBAARD', 'Stephan Baard', 'Namibia', 'Batsman'),
  ('SJBENN', 'Sulieman Benn', 'West Indies', 'Bowler'),
  ('SJMYBURGH', 'Stephan Myburgh', 'Netherlands', 'Batsman'),
  ('SKRAINA', 'Suresh Raina', 'India', 'Batsman'),
  ('SLAMICHHANE', 'Sandeep Lamichhane', 'Nepal', 'Bowler'),
  ('SLMALINGA', 'Lasith Malinga', 'Sri Lanka', 'Bowler'),
  ('SMCURRAN', 'Sam Curran', 'England', 'All-rounder'),
  ('SMSHARIF', 'Safyaan Sharif', 'Scotland', 'Bowler'),
  ('SMSMSENANAYAKE', 'Sachithra Senanayake', 'Sri Lanka', 'Bowler'),
  ('SNNETRAVALKAR', 'Saurabh Netravalkar', 'United States of America', 'Bowler'),
  ('SOHAGGAZI', 'Sohag Gazi', 'Bangladesh', 'All-rounder'),
  ('SOHAIBMAQSOOD', 'Sohaib Maqsood', 'Pakistan', 'Batsman'),
  ('SOHAILTANVIR', 'Sohail Tanvir', 'Pakistan', 'Bowler'),
  ('SOHETMYER', 'Shimron Hetmyer', 'West Indies', 'Batsman'),
  ('SOMPALKAMI', 'Sompal Kami', 'Nepal', 'Bowler'),
  ('SOUMYASARKAR', 'Soumya Sarkar', 'Bangladesh', 'All-rounder'),
  ('SPDSMITH', 'Steve Smith', 'Australia', 'Batsman'),
  ('SPNARINE', 'Sunil Narine', 'West Indies', 'All-rounder'),
  ('SRTAYLOR', 'Steven Taylor', 'United States of America', 'Batsman'),
  ('SRWATSON', 'Shane Watson', 'Australia', 'All-rounder'),
  ('SSAMARAWICKRAMA', 'Sadeera Samarawickrama', 'Sri Lanka', 'Wicketkeeper'),
  ('TABOULT', 'Trent Boult', 'New Zealand', 'Bowler'),
  ('TAMIMIQBAL', 'Tamim Iqbal', 'Bangladesh', 'Batsman'),
  ('TAMSIRIWARDANA', 'Thilina Kandamby', 'Sri Lanka', 'Batsman'),
  ('TANZIDHASAN', 'Tanzid Hasan', 'Bangladesh', 'Batsman'),
  ('TANZIMHASANSAKIB', 'Tanzim Hasan Sakib', 'Bangladesh', 'Bowler'),
  ('TASKINAHMED', 'Taskin Ahmed', 'Bangladesh', 'Bowler'),
  ('TBAVUMA', 'Temba Bavuma', 'South Africa', 'Batsman'),
  ('TGSOUTHEE', 'Tim Southee', 'New Zealand', 'Bowler'),
  ('THDAVID', 'Tim David', 'Australia', 'Batsman'),
  ('TJGPRINGLE', 'Tim Pringle', 'Netherlands', 'All-rounder'),
  ('TLCHATARA', 'Tendai Chatara', 'Zimbabwe', 'Bowler'),
  ('TLSEIFERT', 'Tim Seifert', 'New Zealand', 'Wicketkeeper'),
  ('TLWCOOPER', 'Tom Cooper', 'Netherlands', 'Batsman'),
  ('TMDILSHAN', 'Tillakaratne Dilshan', 'Sri Lanka', 'All-rounder'),
  ('TMHEAD', 'Travis Head', 'Australia', 'Batsman'),
  ('TMUNYONGA', 'Tony Munyonga', 'Zimbabwe', 'Bowler'),
  ('TOWHIDHRIDOY', 'Towhid Hridoy', 'Bangladesh', 'Batsman'),
  ('TSHAMSI', 'Tabraiz Shamsi', 'South Africa', 'Bowler'),
  ('TSMILLS', 'Tymal Mills', 'England', 'Bowler'),
  ('TSTUBBS', 'Tristan Stubbs', 'South Africa', 'Batsman'),
  ('TTBRESNAN', 'Tim Bresnan', 'England', 'All-rounder'),
  ('UMARAKMAL', 'Umar Akmal', 'Pakistan', 'Batsman'),
  ('UMARGUL', 'Umar Gul', 'Pakistan', 'Bowler'),
  ('USMANKHAN', 'Usman Khan', 'Pakistan', 'Batsman'),
  ('UTKHAWAJA', 'Usman Khawaja', 'Australia', 'Batsman'),
  ('VIKRAMJITSINGH', 'Vikramjit Singh', 'Netherlands', 'Batsman'),
  ('VJKINGMA', 'Vivian Kingma', 'Netherlands', 'Bowler'),
  ('VKOHLI', 'Virat Kohli', 'India', 'Batsman'),
  ('WAHABRIAZ', 'Wahab Riaz', 'Pakistan', 'Bowler'),
  ('WDPARNELL', 'Wayne Parnell', 'South Africa', 'All-rounder'),
  ('WGJACKS', 'Will Jacks', 'England', 'All-rounder'),
  ('WIAFERNANDO', 'Avishka Fernando', 'Sri Lanka', 'Batsman'),
  ('WMADHEVERE', 'Wessly Madhevere', 'Zimbabwe', 'All-rounder'),
  ('WPMASAKADZA', 'Wellington Masakadza', 'Zimbabwe', 'Bowler'),
  ('YASIRALICHOWDHURY', 'Yasir Ali', 'Bangladesh', 'Batsman'),
  ('YUVRAJSINGH', 'Yuvraj Singh', 'India', 'All-rounder'),
  ('ZEESHANMAQSOOD', 'Zeeshan Maqsood', 'Oman', 'All-rounder'),
  ('ZEGREEN', 'Zane Green', 'Namibia', 'Wicketkeeper'),
  ('ZIAURRAHMAN', 'Ziaur Rahman', 'Bangladesh', 'All-rounder'),
  ('ZULFIQARBABAR', 'Zulfiqar Babar', 'Pakistan', 'Bowler'),
  ('SACHINTENDULKAR', 'Sachin Tendulkar', 'India', 'Batsman'),
  ('RAHULDRAVID', 'Rahul Dravid', 'India', 'Batsman'),
  ('VABORODE', 'VVS Laxman', 'India', 'Batsman'),
  ('SOURAVGANGULY', 'Sourav Ganguly', 'India', 'Batsman'),
  ('VIRENDERSWAG', 'Virender Sehwag', 'India', 'Batsman'),
  ('ANILKUMBLE', 'Anil Kumble', 'India', 'Bowler'),
  ('HARBHAJAN', 'Harbhajan Singh', 'India', 'Bowler'),
  ('ZAHEER', 'Zaheer Khan', 'India', 'Bowler'),
  ('IRFANPATHAN', 'Irfan Pathan', 'India', 'All-rounder'),
  ('GAUTAMGAMBHIR', 'Gautam Gambhir', 'India', 'Batsman'),
  ('ISHANT', 'Ishant Sharma', 'India', 'Bowler'),
  ('UMESH', 'Umesh Yadav', 'India', 'Bowler'),
  ('PRITHVISHAW', 'Prithvi Shaw', 'India', 'Batsman'),
  ('IYER', 'Shreyas Iyer', 'India', 'Batsman'),
  ('SAMSONR', 'Sanju Samson', 'India', 'Wicketkeeper'),
  ('RUTURAJ', 'Ruturaj Gaikwad', 'India', 'Batsman'),
  ('YASHASWI', 'Yashasvi Jaiswal', 'India', 'Batsman'),
  ('SHUBHMAN', 'Shubman Gill', 'India', 'Batsman'),
  ('TILAKVARMA', 'Tilak Varma', 'India', 'Batsman'),
  ('RINKU', 'Rinku Singh', 'India', 'Batsman'),
  ('RAVIBISHNOI', 'Ravi Bishnoi', 'India', 'Bowler'),
  ('MUKESHKUMAR', 'Mukesh Kumar', 'India', 'Bowler'),
  ('AVESH', 'Avesh Khan', 'India', 'Bowler'),
  ('RICKYPONTING', 'Ricky Ponting', 'Australia', 'Batsman'),
  ('ADAMGILCHRIST', 'Adam Gilchrist', 'Australia', 'Wicketkeeper'),
  ('MATTHEWHAYD', 'Matthew Hayden', 'Australia', 'Batsman'),
  ('JUSTINLANGER', 'Justin Langer', 'Australia', 'Batsman'),
  ('MICHAELCLARKE', 'Michael Clarke', 'Australia', 'Batsman'),
  ('BRETLEE', 'Brett Lee', 'Australia', 'Bowler'),
  ('GLENNMCGRATH', 'Glenn McGrath', 'Australia', 'Bowler'),
  ('SHANEWARNED', 'Shane Warne', 'Australia', 'Bowler'),
  ('MICHAELHUSSEY', 'Michael Hussey', 'Australia', 'Batsman'),
  ('ANDREWSYMONDS', 'Andrew Symonds', 'Australia', 'All-rounder'),
  ('NATHANLYON', 'Nathan Lyon', 'Australia', 'Bowler'),
  ('ALEXCAREY', 'Alex Carey', 'Australia', 'Wicketkeeper'),
  ('CAMERONGREEN', 'Cameron Green', 'Australia', 'All-rounder'),
  ('MARNUS', 'Marnus Labuschagne', 'Australia', 'Batsman'),
  ('JAKFRASER', 'Jake Fraser-McGurk', 'Australia', 'Batsman'),
  ('JOSHING', 'Josh Inglis', 'Australia', 'Wicketkeeper'),
  ('MATTSHORT', 'Matt Short', 'Australia', 'All-rounder'),
  ('SPENCERRJOHNSON', 'Spencer Johnson', 'Australia', 'Bowler'),
  ('JOEROOT', 'Joe Root', 'England', 'Batsman'),
  ('JIMMYANDERSON', 'James Anderson', 'England', 'Bowler'),
  ('KEVINPIETERSN', 'Kevin Pietersen', 'England', 'Batsman'),
  ('ANDREWFLINTOFF', 'Andrew Flintoff', 'England', 'All-rounder'),
  ('ANDREWSTRAUSS', 'Andrew Strauss', 'England', 'Batsman'),
  ('ALASTAIRCOOK', 'Alastair Cook', 'England', 'Batsman'),
  ('IANBELL', 'Ian Bell', 'England', 'Batsman'),
  ('GRAEMESWANN', 'Graeme Swann', 'England', 'Bowler'),
  ('MATTPRIOR', 'Matt Prior', 'England', 'Wicketkeeper'),
  ('JACKCRAWLEY', 'Zak Crawley', 'England', 'Batsman'),
  ('BENDUCKETT', 'Ben Duckett', 'England', 'Batsman'),
  ('JAMIEVINCE', 'James Vince', 'England', 'Batsman'),
  ('OLLYPOPE', 'Ollie Pope', 'England', 'Batsman'),
  ('GURSINGH', 'Gus Atkinson', 'England', 'Bowler'),
  ('MATTHEWPOTTS', 'Matthew Potts', 'England', 'Bowler'),
  ('SHOAIBASHIR', 'Shoaib Bashir', 'England', 'Bowler'),
  ('JACOBBETHELL', 'Jacob Bethell', 'England', 'All-rounder'),
  ('JAMISC', 'Jamie Smith', 'England', 'Wicketkeeper'),
  ('BRENDONMCCULLUM', 'Brendon McCullum', 'New Zealand', 'Wicketkeeper'),
  ('DANIELVETTORI', 'Daniel Vettori', 'New Zealand', 'All-rounder'),
  ('NATHANASTLE', 'Nathan Astle', 'New Zealand', 'Batsman'),
  ('STEPHENFLEMING', 'Stephen Fleming', 'New Zealand', 'Batsman'),
  ('JACOBORAM', 'Jacob Oram', 'New Zealand', 'All-rounder'),
  ('TOMBLUNDELL', 'Tom Blundell', 'New Zealand', 'Wicketkeeper'),
  ('WILLLOUNG', 'Will Young', 'New Zealand', 'Batsman'),
  ('RACHINRAV', 'Rachin Ravindra', 'New Zealand', 'All-rounder'),
  ('MARKCHAPMAN', 'Mark Chapman', 'New Zealand', 'Batsman'),
  ('MATTHENRY', 'Matt Henry', 'New Zealand', 'Bowler'),
  ('KYLEJAMIESON', 'Kyle Jamieson', 'New Zealand', 'All-rounder'),
  ('MICHAELBRACEWELL', 'Michael Bracewell', 'New Zealand', 'All-rounder'),
  ('JACQUESKALLIS', 'Jacques Kallis', 'South Africa', 'All-rounder'),
  ('GRAEMESMITH', 'Graeme Smith', 'South Africa', 'Batsman'),
  ('MARKBOUCHER', 'Mark Boucher', 'South Africa', 'Wicketkeeper'),
  ('SHANEPOLK', 'Shaun Pollock', 'South Africa', 'All-rounder'),
  ('MAKHAYANTINI', 'Makhaya Ntini', 'South Africa', 'Bowler'),
  ('LANCEKLING', 'Lance Klusener', 'South Africa', 'All-rounder'),
  ('HERBERTGIBBS', 'Herschelle Gibbs', 'South Africa', 'Batsman'),
  ('ABMORKEL', 'Morne Morkel', 'South Africa', 'Bowler'),
  ('VERNONPHILANDER', 'Vernon Philander', 'South Africa', 'All-rounder'),
  ('RYANRICKER', 'Ryan Rickelton', 'South Africa', 'Batsman'),
  ('TONYDEZ', 'Tony de Zorzi', 'South Africa', 'Batsman'),
  ('CORBIN', 'Corbin Bosch', 'South Africa', 'All-rounder'),
  ('KWENAWEBER', 'Kwena Maphaka', 'South Africa', 'Bowler'),
  ('WASIMAKRAM', 'Wasim Akram', 'Pakistan', 'Bowler'),
  ('WAQARYOUNIS', 'Waqar Younis', 'Pakistan', 'Bowler'),
  ('INZAMAM', 'Inzamam-ul-Haq', 'Pakistan', 'Batsman'),
  ('MIANDAD', 'Javed Miandad', 'Pakistan', 'Batsman'),
  ('SAQLAINJAB', 'Saqlain Mushtaq', 'Pakistan', 'Bowler'),
  ('MISBAHULHAQ', 'Misbah-ul-Haq', 'Pakistan', 'Batsman'),
  ('YOUNISKHAN', 'Younis Khan', 'Pakistan', 'Batsman'),
  ('MOHAMMADYOUSUF', 'Mohammad Yousuf', 'Pakistan', 'Batsman'),
  ('ABDULRAZZAQ', 'Abdul Razzaq', 'Pakistan', 'All-rounder'),
  ('SALMANKHAN', 'Salman Ali Agha', 'Pakistan', 'All-rounder'),
  ('ABRAR', 'Abrar Ahmed', 'Pakistan', 'Bowler'),
  ('KHURRAMSHAHZAD', 'Khurram Shahzad', 'Pakistan', 'Bowler'),
  ('SAUDSHAKEEL', 'Saud Shakeel', 'Pakistan', 'Batsman'),
  ('ABDULLAHSHAFIQ', 'Abdullah Shafique', 'Pakistan', 'Batsman'),
  ('AAMIRJAMAL', 'Aamer Jamal', 'Pakistan', 'All-rounder'),
  ('BRIANLARA', 'Brian Lara', 'West Indies', 'Batsman'),
  ('CURTLYAMBROSE', 'Curtly Ambrose', 'West Indies', 'Bowler'),
  ('COURTNEWALSH', 'Courtney Walsh', 'West Indies', 'Bowler'),
  ('VIVIVRICHARDS', 'Viv Richards', 'West Indies', 'Batsman'),
  ('GORDONGREEN', 'Gordon Greenidge', 'West Indies', 'Batsman'),
  ('DESMONDHAYN', 'Desmond Haynes', 'West Indies', 'Batsman'),
  ('MALCOLMMARSHALL', 'Malcolm Marshall', 'West Indies', 'Bowler'),
  ('JOELGARNER', 'Joel Garner', 'West Indies', 'Bowler'),
  ('CLIVELLOYD', 'Clive Lloyd', 'West Indies', 'Batsman'),
  ('SHIVNARINE', 'Shivnarine Chanderpaul', 'West Indies', 'Batsman'),
  ('JASONHOLDER', 'Jason Holder', 'West Indies', 'All-rounder'),
  ('KEMAR', 'Kemar Roach', 'West Indies', 'Bowler'),
  ('KRAIGBRATH', 'Kraigg Brathwaite', 'West Indies', 'Batsman'),
  ('MURALISRIL', 'Muttiah Muralitharan', 'Sri Lanka', 'Bowler'),
  ('SANATHJ', 'Sanath Jayasuriya', 'Sri Lanka', 'All-rounder'),
  ('ARAVINDDASILVA', 'Aravinda de Silva', 'Sri Lanka', 'Batsman'),
  ('CHAMINDAVAAS', 'Chaminda Vaas', 'Sri Lanka', 'Bowler'),
  ('MARVANATTA', 'Marvan Atapattu', 'Sri Lanka', 'Batsman'),
  ('ROMESKALUWITHARANA', 'Romesh Kaluwitharana', 'Sri Lanka', 'Wicketkeeper'),
  ('DIMUTHJAY', 'Dimuth Karunaratne', 'Sri Lanka', 'Batsman'),
  ('ASITHAFERNANDO', 'Asitha Fernando', 'Sri Lanka', 'Bowler'),
  ('LAHIRUMADUSH', 'Lahiru Madushanka', 'Sri Lanka', 'All-rounder'),
  ('ABDULABBI', 'Abdul Razzaq', 'Pakistan', 'All-rounder'),
  ('MITCHELLJOHNSON', 'Mitchell Johnson', 'Australia', 'Bowler'),
  ('SANGAKKARA', 'Kumar Sangakkara', 'Sri Lanka', 'Wicketkeeper'),
  ('HASHIMAMLA', 'Hashim Amla', 'South Africa', 'Batsman'),
  ('CHRISTGAYLE', 'Chris Gayle', 'West Indies', 'Batsman'),
  ('MAHENDRASINGH', 'MS Dhoni', 'India', 'Wicketkeeper'),
  ('BENMCDERMOTT', 'Ben McDermott', 'Australia', 'Batsman'),
  ('JOSHUADASU', 'Joshua Da Silva', 'West Indies', 'Wicketkeeper'),
  ('MATTHEWFORDE', 'Matthew Forde', 'West Indies', 'Bowler'),
  ('SHAMARJOSEPH', 'Shamar Joseph', 'West Indies', 'Bowler'),
  ('JAYDENSPREAK', 'Jayden Seales', 'West Indies', 'Bowler'),
  ('TEYONSEALY', 'Tevin Imlach', 'West Indies', 'Wicketkeeper'),
  ('ALICKATHANAS', 'Alick Athanaze', 'West Indies', 'Batsman'),
  ('KAVEMH', 'Kavem Hodge', 'West Indies', 'Batsman'),
  ('MIKAYLAJOH', 'Mikyle Louis', 'West Indies', 'Batsman'),
  ('GUDAKESH', 'Gudakesh Motie', 'West Indies', 'Bowler'),
  ('AAMIRSO', 'Aamir Sohail', 'Pakistan', 'Batsman'),
  ('ATHAR', 'Athar Ali Khan', 'Bangladesh', 'Batsman'),
  ('AMINULISLAM', 'Aminul Islam', 'Bangladesh', 'Batsman'),
  ('AKRAMKHAN', 'Akram Khan', 'Bangladesh', 'Batsman'),
  ('HABIBULBASHAR', 'Habibul Bashar', 'Bangladesh', 'Batsman'),
  ('MOHAMMADASHRAFUL', 'Mohammad Ashraful', 'Bangladesh', 'Batsman'),
  ('ABDULERRAB', 'Abdur Razzak', 'Bangladesh', 'Bowler'),
  ('RUBELHOSSAIN', 'Rubel Hossain', 'Bangladesh', 'Bowler'),
  ('TAIJUL', 'Taijul Islam', 'Bangladesh', 'Bowler'),
  ('MEHIDY', 'Mehidy Hasan Miraz', 'Bangladesh', 'All-rounder'),
  ('MOMINUL', 'Mominul Haque', 'Bangladesh', 'Batsman'),
  ('ZAKIRCLARKE', 'Zakir Hasan', 'Bangladesh', 'Batsman'),
  ('NAYEEM', 'Nayeem Hasan', 'Bangladesh', 'Bowler'),
  ('HASAN', 'Hasan Mahmud', 'Bangladesh', 'Bowler'),
  ('ANDYROB', 'Andy Flower', 'Zimbabwe', 'Wicketkeeper'),
  ('HEATHSTREAK', 'Heath Streak', 'Zimbabwe', 'All-rounder'),
  ('GRANF', 'Grant Flower', 'Zimbabwe', 'All-rounder'),
  ('HENRYO', 'Henry Olonga', 'Zimbabwe', 'Bowler'),
  ('ALISTAIRCAMP', 'Alistair Campbell', 'Zimbabwe', 'Batsman'),
  ('NEILJ', 'Neil Johnson', 'Zimbabwe', 'All-rounder'),
  ('MURRAYG', 'Murray Goodwin', 'Zimbabwe', 'Batsman'),
  ('STUARTREP', 'Stuart Carlisle', 'Zimbabwe', 'Batsman'),
  ('TATENDATAIBU', 'Tatenda Taibu', 'Zimbabwe', 'Wicketkeeper'),
  ('BRENDONTAYLOR', 'Brendan Taylor', 'Zimbabwe', 'Batsman'),
  ('ELTONCHIG', 'Elton Chigumbura', 'Zimbabwe', 'All-rounder'),
  ('HAMILTONMASA', 'Hamilton Masakadza', 'Zimbabwe', 'Batsman'),
  ('CLIVE', 'Clive Madande', 'Zimbabwe', 'Wicketkeeper'),
  ('DIONNYR', 'Dion Myers', 'Zimbabwe', 'All-rounder'),
  ('JOHARIKIM', 'Joylord Gumbie', 'Zimbabwe', 'Batsman'),
  ('BRIANBEN', 'Brian Bennett', 'Zimbabwe', 'Batsman'),
  ('WILLIAMPORTERFIELD', 'William Porterfield', 'Ireland', 'Batsman'),
  ('KEVINOBRIEN', 'Kevin O''Brien', 'Ireland', 'All-rounder'),
  ('TIMMORISH', 'Tim Murtagh', 'Ireland', 'Bowler'),
  ('ANDYMCBRINE', 'Andy McBrine', 'Ireland', 'All-rounder'),
  ('CRAIGHY', 'Craig Young', 'Ireland', 'Bowler'),
  ('GRAHAMFORDE', 'Graham Hume', 'Ireland', 'Bowler'),
  ('FIONN', 'Fionn Hand', 'Ireland', 'Bowler'),
  ('KAGISOQESHILE', 'Kyle Verreynne', 'South Africa', 'Wicketkeeper'),
  ('WITANAAN', 'Wiaan Mulder', 'South Africa', 'All-rounder'),
  ('SISANDAMAGEN', 'Sisanda Magala', 'South Africa', 'Bowler'),
  ('GERALDC', 'Gerald Coetzee', 'South Africa', 'Bowler'),
  ('DONOVALFER', 'Donovan Ferreira', 'South Africa', 'Batsman'),
  ('NANDREBURGER', 'Nandre Burger', 'South Africa', 'Bowler'),
  ('CHETESHWARPU', 'Cheteshwar Pujara', 'India', 'Batsman'),
  ('WRIDDHI', 'Wriddhiman Saha', 'India', 'Wicketkeeper'),
  ('AJINKYA', 'Ajinkya Rahane', 'India', 'Batsman'),
  ('MAYANKAGAR', 'Mayank Agarwal', 'India', 'Batsman'),
  ('HANUMAVI', 'Hanuma Vihari', 'India', 'Batsman'),
  ('KARUNAI', 'Karun Nair', 'India', 'Batsman'),
  ('PARTHIVPAT', 'Parthiv Patel', 'India', 'Wicketkeeper'),
  ('JAYANTYADAV', 'Jayant Yadav', 'India', 'All-rounder'),
  ('SHARDUL', 'Shardul Thakur', 'India', 'All-rounder'),
  ('NAVIDKULKR', 'Navdeep Saini', 'India', 'Bowler'),
  ('SIDDHU', 'Washington Sundar', 'India', 'All-rounder'),
  ('AKASHDEEP', 'Akash Deep', 'India', 'Bowler'),
  ('DHRUVJUREL', 'Dhruv Jurel', 'India', 'Wicketkeeper'),
  ('NITI', 'Nitish Kumar Reddy', 'India', 'All-rounder'),
  ('PRASIDHKR', 'Prasidh Krishna', 'India', 'Bowler'),
  ('DEVADK', 'Devdutt Padikkal', 'India', 'Batsman'),
  ('SARFARAZKHAN', 'Sarfaraz Khan', 'India', 'Batsman'),
  ('ABHIMANYUE', 'Abhimanyu Easwaran', 'India', 'Batsman'),
  ('HARISHK', 'Harshit Rana', 'India', 'Bowler'),
  ('RASHIDKHAN', 'Rashid Khan', 'Afghanistan', 'Bowler'),
  ('MOHAMMADNABI', 'Mohammad Nabi', 'Afghanistan', 'All-rounder'),
  ('RAHMANULLAHGURBAZ', 'Rahmanullah Gurbaz', 'Afghanistan', 'Wicketkeeper'),
  ('IBRAHIMZADRAN', 'Ibrahim Zadran', 'Afghanistan', 'Batsman'),
  ('NAJIBULLAHZADRAN', 'Najibullah Zadran', 'Afghanistan', 'Batsman'),
  ('HAZRATULLAHZAZAI', 'Hazratullah Zazai', 'Afghanistan', 'Batsman'),
  ('AZMATULLAHOMARZAI', 'Azmatullah Omarzai', 'Afghanistan', 'All-rounder'),
  ('GULBADINNAIB', 'Gulbadin Naib', 'Afghanistan', 'All-rounder'),
  ('MUJEEBUR', 'Mujeeb Ur Rahman', 'Afghanistan', 'Bowler'),
  ('NAVEENULHAQ', 'Naveen-ul-Haq', 'Afghanistan', 'Bowler'),
  ('FAZALHAQFAROOQI', 'Fazalhaq Farooqi', 'Afghanistan', 'Bowler'),
  ('KARIMJANAT', 'Karim Janat', 'Afghanistan', 'All-rounder'),
  ('NOORAHMAD', 'Noor Ahmad', 'Afghanistan', 'Bowler'),
  ('FAREEDAHMAD', 'Fareed Ahmad', 'Afghanistan', 'Bowler'),
  ('MOHAMMADISHAQ', 'Mohammad Ishaq', 'Afghanistan', 'Batsman'),
  ('NANGYALKHAROTI', 'Nangyal Kharoti', 'Afghanistan', 'Bowler'),
  ('SEDIQULLAHATAL', 'Sediqullah Atal', 'Afghanistan', 'Batsman'),
  ('SALEEMSAFI', 'Saleem Safi', 'Afghanistan', 'All-rounder'),
  ('ASGHARAFGHAN', 'Asghar Afghan', 'Afghanistan', 'Batsman'),
  ('HASHMATULLAHSHAHIDI', 'Hashmatullah Shahidi', 'Afghanistan', 'Batsman'),
  ('USMANGHANI', 'Usman Ghani', 'Afghanistan', 'Batsman'),
  ('DAWLATZADRAN', 'Dawlat Zadran', 'Afghanistan', 'Bowler'),
  ('HAMIDHASSAN', 'Hamid Hassan', 'Afghanistan', 'Bowler'),
  ('SHAPOORZADRAN', 'Shapoor Zadran', 'Afghanistan', 'Bowler'),
  ('SAMIULLAHSHINWARI', 'Samiullah Shinwari', 'Afghanistan', 'All-rounder'),
  ('SHAFIQULLAHSHAFAQ', 'Shafiqullah Shafaq', 'Afghanistan', 'Wicketkeeper'),
  ('SAADBINZAFAR', 'Saad Bin Zafar', 'Canada', 'All-rounder'),
  ('AARONJOHNSON', 'Aaron Johnson', 'Canada', 'Batsman'),
  ('DILONHEYLIGER', 'Dilon Heyliger', 'Canada', 'Bowler'),
  ('DILPREETBAJWA', 'Dilpreet Bajwa', 'Canada', 'All-rounder'),
  ('HARSHTHAKER', 'Harsh Thaker', 'Canada', 'Bowler'),
  ('JEREMYGORDON', 'Jeremy Gordon', 'Canada', 'Bowler'),
  ('JUNAIDSIDDIQUI', 'Junaid Siddiqui', 'Canada', 'All-rounder'),
  ('KALEEMSANA', 'Kaleem Sana', 'Canada', 'Bowler'),
  ('KANWARPALTATHGUR', 'Kanwarpal Tathgur', 'Canada', 'Batsman'),
  ('NAVNEETDHALIWAL', 'Navneet Dhaliwal', 'Canada', 'All-rounder'),
  ('NICHOLASKIRTON', 'Nicholas Kirton', 'Canada', 'Batsman'),
  ('PARGATSINGH', 'Pargat Singh', 'Canada', 'Batsman'),
  ('RAVINDERPALSINGH', 'Ravinderpal Singh', 'Canada', 'Bowler'),
  ('RAYYANKHANPATHAN', 'Rayyankhan Pathan', 'Canada', 'Batsman'),
  ('SHREYASMOVVA', 'Shreyas Movva', 'Canada', 'Wicketkeeper'),
  ('TAJINDERSINGH', 'Tajinder Singh', 'Canada', 'Batsman'),
  ('AADITYAVARADHARAJAN', 'Aaditya Varadharajan', 'Canada', 'Batsman'),
  ('AMMARKHALID', 'Ammar Khalid', 'Canada', 'Bowler'),
  ('JATINDERMATHARU', 'Jatinder Matharu', 'Canada', 'Bowler'),
  ('PARVEENKUMAR', 'Parveen Kumar', 'Canada', 'All-rounder'),
  ('MUHAMMADWASEEM', 'Muhammad Waseem', 'United Arab Emirates', 'Batsman'),
  ('ALISHANSHARAFU', 'Alishan Sharafu', 'United Arab Emirates', 'Batsman'),
  ('ASIFKHANUAE', 'Asif Khan', 'United Arab Emirates', 'Batsman'),
  ('CHIRAGSURI', 'Chirag Suri', 'United Arab Emirates', 'Batsman'),
  ('ROHANMUSTAFA', 'Rohan Mustafa', 'United Arab Emirates', 'All-rounder'),
  ('AHMEDRAZA', 'Ahmed Raza', 'United Arab Emirates', 'All-rounder'),
  ('ZAHOORKHANUAE', 'Zahoor Khan', 'United Arab Emirates', 'Bowler'),
  ('CPRIZWAN', 'CP Rizwan', 'United Arab Emirates', 'Wicketkeeper'),
  ('JUNAIDSIDDIQUEUAE', 'Junaid Siddique', 'United Arab Emirates', 'Bowler'),
  ('BASILDHAMANI', 'Basil Hameed', 'United Arab Emirates', 'Bowler'),
  ('KASIFRABBANI', 'Kashif Daud', 'United Arab Emirates', 'All-rounder'),
  ('VRIITIYAARAVIND', 'Vriitya Aravind', 'United Arab Emirates', 'Wicketkeeper'),
  ('ARYANSHSHARMA', 'Aryansh Sharma', 'United Arab Emirates', 'All-rounder'),
  ('DHRUVPARASHAR', 'Dhruv Parashar', 'United Arab Emirates', 'Bowler'),
  ('ETHANDSOUZA', 'Ethan D''Souza', 'United Arab Emirates', 'Batsman'),
  ('RAHULCHOPRA', 'Rahul Chopra', 'United Arab Emirates', 'Batsman'),
  ('KARANROOPSINGH', 'Karan Roopsingh', 'United Arab Emirates', 'Bowler'),
  ('HAZARDANIEL', 'Hazrat Bilal', 'United Arab Emirates', 'Bowler'),
  ('BRIANMASABA', 'Brian Masaba', 'Uganda', 'All-rounder'),
  ('SIMONSSESAZI', 'Simon Ssesazi', 'Uganda', 'Batsman'),
  ('ROGERMUKASA', 'Roger Mukasa', 'Uganda', 'All-rounder'),
  ('COSMASKYEWUTA', 'Cosmas Kyewuta', 'Uganda', 'Batsman'),
  ('DINESHNAKRANI', 'Dinesh Nakrani', 'Uganda', 'All-rounder'),
  ('FREDACHELAM', 'Fred Achelam', 'Uganda', 'Bowler'),
  ('KENNETHWAISWA', 'Kenneth Waiswa', 'Uganda', 'Batsman'),
  ('ALPESHRAMJANI', 'Alpesh Ramjani', 'Uganda', 'All-rounder'),
  ('FRANKNSUBUGA', 'Frank Nsubuga', 'Uganda', 'Bowler'),
  ('HENRYSSENYONDO', 'Henry Ssenyondo', 'Uganda', 'Bowler'),
  ('BILALHASSUN', 'Bilal Hassun', 'Uganda', 'Bowler'),
  ('ROBINSONOBUYA', 'Robinson Obuya', 'Uganda', 'All-rounder'),
  ('RIAZATALISHAH', 'Riazat Ali Shah', 'Uganda', 'Batsman'),
  ('JUMAMIYAJI', 'Juma Miyaji', 'Uganda', 'Batsman'),
  ('RONAKPATEL', 'Ronak Patel', 'Uganda', 'Wicketkeeper'),
  ('INNOCENTMWEBAZE', 'Innocent Mwebaze', 'Uganda', 'Batsman'),
  ('RONALDLUTAAYA', 'Ronald Lutaaya', 'Uganda', 'Bowler'),
  ('ASSADVALA', 'Assad Vala', 'Papua New Guinea', 'All-rounder'),
  ('CJAMINI', 'CJ Amini', 'Papua New Guinea', 'All-rounder'),
  ('ALEINAO', 'Alei Nao', 'Papua New Guinea', 'All-rounder'),
  ('CHADSOPER', 'Chad Soper', 'Papua New Guinea', 'All-rounder'),
  ('HILAVARE', 'Hila Vare', 'Papua New Guinea', 'Wicketkeeper'),
  ('HIRIHIRI', 'Hiri Hiri', 'Papua New Guinea', 'All-rounder'),
  ('JACKGARDNER', 'Jack Gardner', 'Papua New Guinea', 'All-rounder'),
  ('JOHNKARIKO', 'John Kariko', 'Papua New Guinea', 'Bowler'),
  ('KABUAMOREA', 'Kabua Vagi Morea', 'Papua New Guinea', 'Bowler'),
  ('KIPLINGDORIGA', 'Kipling Doriga', 'Papua New Guinea', 'Wicketkeeper'),
  ('LEGASIAKA', 'Lega Siaka', 'Papua New Guinea', 'All-rounder'),
  ('NORMANVANUA', 'Norman Vanua', 'Papua New Guinea', 'Bowler'),
  ('SEMAKAMEA', 'Sema Kamea', 'Papua New Guinea', 'Bowler'),
  ('SESEBAU', 'Sese Bau', 'Papua New Guinea', 'All-rounder'),
  ('TONYURA', 'Tony Ura', 'Papua New Guinea', 'Batsman'),
  ('WAYNEMADSEN', 'Wayne Madsen', 'Italy', 'Batsman'),
  ('MARCUSCAMPOPIANO', 'Marcus Campopiano', 'Italy', 'Wicketkeeper'),
  ('GIANPIEROMEADE', 'Gian Piero Meade', 'Italy', 'Batsman'),
  ('ZAINALI', 'Zain Ali', 'Italy', 'Bowler'),
  ('ALIHASAN', 'Ali Hasan', 'Italy', 'Bowler'),
  ('CRISHANJORGE', 'Crishan Jorge', 'Italy', 'Bowler'),
  ('HARRYMANENTI', 'Harry Manenti', 'Italy', 'All-rounder'),
  ('ANTHONYMOSCA', 'Anthony Mosca', 'Italy', 'All-rounder'),
  ('JUSTINMOSCA', 'Justin Mosca', 'Italy', 'All-rounder'),
  ('SYEDNAQVI', 'Syed Naqvi', 'Italy', 'Bowler'),
  ('BENJAMINMANENTI', 'Benjamin Manenti', 'Italy', 'Bowler'),
  ('JASPREETSINGH', 'Jaspreet Singh', 'Italy', 'Bowler'),
  ('JJSMUTS', 'JJ Smuts', 'Italy', 'All-rounder'),
  ('GRANTSTEWART', 'Grant Stewart', 'Italy', 'All-rounder'),
  ('THOMASDRACA', 'Thomas Draca', 'Italy', 'Bowler'),
  ('SUNDEEPJORA', 'Sundeep Jora', 'Nepal', 'Batsman'),
  ('AARIFSHEIKH', 'Aarif Sheikh', 'Nepal', 'All-rounder'),
  ('BASIRAHAMAD', 'Basir Ahamad', 'Nepal', 'All-rounder'),
  ('NANDANYADAV', 'Nandan Yadav', 'Nepal', 'All-rounder'),
  ('LALITRAJBANSHI', 'Lalit Rajbanshi', 'Nepal', 'Bowler'),
  ('SHERMALLA', 'Sher Malla', 'Nepal', 'Bowler'),
  ('LOKESHBAM', 'Lokesh Bam', 'Nepal', 'Batsman'),
  ('MONANKPATEL', 'Monank Patel', 'United States of America', 'Wicketkeeper'),
  ('JESSYSINGH', 'Jessy Singh', 'United States of America', 'Bowler'),
  ('SHADLEYVANSCHALKWYK', 'Shadley Van Schalkwyk', 'United States of America', 'Bowler'),
  ('NISARGPATEL', 'Nisarg Patel', 'United States of America', 'All-rounder');

-- ============================================
-- PUZZLES DATA IMPORT
-- ============================================

INSERT INTO puzzles (id, puzzle_date, venue, team1_score, team2_score, result, players_in_match, target_player_id, target_player_team, target_player_role, tournament) VALUES
  (1, '2026-01-15', 'Eden Gardens', '155/9 (19.1 overs)', '161/6 (19.4 overs)', 'Team 2 won by 4 wickets', '["JJROY","ADHALES","JEROOT","EJGMORGAN","JCBUTTLER","BASTOKES","MMALI","CJJORDAN","DJWILLEY","LEPLUNKETT","AURASHID","JCHARLES","CHGAYLE","MNSAMUELS","LMPSIMMONS","DJBRAVO","ADRUSSELL","DJGSAMMY","CRBRATHWAITE","DRAMDIN","SBADREE","SJBENN"]'::jsonb, 'MNSAMUELS', 'West Indies', 'All-rounder', 'T20 World Cup 2024'),
  (2, '2026-01-16', 'Dubai International Cricket Stadium', '151/7 (19.5 overs)', '152/0 (17.3 overs)', 'Team 2 won by 10 wickets', '["KLRAHUL","RGSHARMA","VKOHLI","SAYADAV","RRPANT","RAJADEJA","HHPANDYA","BKUMAR","MOHAMMEDSHAMI","JJBUMRAH","CVVARUN","MOHAMMADRIZWAN","BABARAZAM","FAKHARZAMAN","MOHAMMADHAFEEZ","SHOAIBMALIK","ASIFALI","SHADABKHAN","IMADWASIM","HASANALI","HARISRAUF","SHAHEENSHAHAFRIDI"]'::jsonb, 'SHAHEENSHAHAFRIDI', 'Pakistan', 'Bowler', 'T20 World Cup 2024'),
  (3, '2026-01-17', 'Melbourne Cricket Ground', '159/8 (20 overs)', '160/6 (19.5 overs)', 'Team 2 won by 4 wickets', '["MOHAMMADRIZWAN","BABARAZAM","SHANMASOOD","IFTIKHARAHMED","SHADABKHAN","HAIDERALI","MOHAMMADNAWAZ","ASIFALI","SHAHEENSHAHAFRIDI","HARISRAUF","NASEEMSHAH","KLRAHUL","RGSHARMA","VKOHLI","SAYADAV","ARPATEL","HHPANDYA","KDKARTHIK","RASHWIN","MOHAMMEDSHAMI","BKUMAR","ARSHDEEPSINGH"]'::jsonb, 'VKOHLI', 'India', 'Batsman', 'T20 World Cup 2024'),
  (4, '2026-01-18', 'Adelaide Oval', '168/6 (19.3 overs)', '170/0 (15.3 overs)', 'Team 2 won by 10 wickets', '["KLRAHUL","RGSHARMA","VKOHLI","SAYADAV","HHPANDYA","RRPANT","RASHWIN","ARPATEL","BKUMAR","MOHAMMEDSHAMI","ARSHDEEPSINGH","JCBUTTLER","ADHALES","PDSALT","BASTOKES","HCBROOK","LSLIVINGSTONE","MMALI","SMCURRAN","CRWOAKES","CJJORDAN","AURASHID"]'::jsonb, 'ADHALES', 'England', 'Batsman', 'T20 World Cup 2024'),
  (5, '2026-01-19', 'Melbourne Cricket Ground', '137/8 (19.1 overs)', '138/5 (18.4 overs)', 'Team 2 won by 5 wickets', '["MOHAMMADRIZWAN","BABARAZAM","MOHAMMADHARIS","SHANMASOOD","IFTIKHARAHMED","SHADABKHAN","MOHAMMADNAWAZ","MOHAMMADWASIM","SHAHEENSHAHAFRIDI","HARISRAUF","NASEEMSHAH","JCBUTTLER","ADHALES","PDSALT","BASTOKES","HCBROOK","MMALI","LSLIVINGSTONE","SMCURRAN","CRWOAKES","CJJORDAN","AURASHID"]'::jsonb, 'SMCURRAN', 'England', 'All-rounder', 'T20 World Cup 2024'),
  (6, '2026-01-20', 'Kensington Oval, Bridgetown, Barbados', '176/7 (19.1 overs)', '169/8 (19.4 overs)', 'Team 1 won by 7 runs', '["RGSHARMA","VKOHLI","RRPANT","SAYADAV","ARPATEL","SDUBE","HHPANDYA","RAJADEJA","KULDEEPYADAV","ARSHDEEPSINGH","JJBUMRAH","RRHENDRICKS","QDEKOCK","AKMARKRAM","TSTUBBS","HKLAASEN","DAMILLER","MJANSEN","KAMAHARAJ","KRABADA","ANORTJE","TSHAMSI"]'::jsonb, 'VKOHLI', 'India', 'Batsman', 'T20 World Cup 2024'),
  (7, '2026-01-21', 'Wankhede Stadium', '182/6 (20 overs)', '183/4 (18.1 overs)', 'Team 2 won by 6 wickets', '["JJROY","ADHALES","JEROOT","JCBUTTLER","EJGMORGAN","BASTOKES","MMALI","CJJORDAN","AURASHID","DJWILLEY","RJWTOPLEY","JCHARLES","CHGAYLE","MNSAMUELS","DRAMDIN","DJBRAVO","ADRUSSELL","DJGSAMMY","CRBRATHWAITE","SBADREE","JETAYLOR","SJBENN"]'::jsonb, 'CHGAYLE', 'West Indies', 'Batsman', 'T20 World Cup 2024'),
  (8, '2026-01-22', 'Nassau County International Cricket Stadium, New York', '119/10 (18.5 overs)', '113/7 (19.4 overs)', 'Team 1 won by 6 runs', '["RGSHARMA","VKOHLI","RRPANT","ARPATEL","SAYADAV","SDUBE","HHPANDYA","RAJADEJA","ARSHDEEPSINGH","JJBUMRAH","MOHAMMEDSIRAJ","MOHAMMADRIZWAN","BABARAZAM","USMANKHAN","FAKHARZAMAN","IMADWASIM","SHADABKHAN","IFTIKHARAHMED","SHAHEENSHAHAFRIDI","NASEEMSHAH","MOHAMMADAMIR","HARISRAUF"]'::jsonb, 'JJBUMRAH', 'India', 'Bowler', 'T20 World Cup 2024'),
  (9, '2026-01-23', 'Providence Stadium, Guyana', '171/7 (19.1 overs)', '103/10 (16.4 overs)', 'Team 1 won by 68 runs', '["RGSHARMA","VKOHLI","RRPANT","SAYADAV","HHPANDYA","RAJADEJA","SDUBE","ARPATEL","ARSHDEEPSINGH","KULDEEPYADAV","JJBUMRAH","PDSALT","JCBUTTLER","MMALI","JMBAIRSTOW","HCBROOK","SMCURRAN","LSLIVINGSTONE","CJJORDAN","JCARCHER","AURASHID","RJWTOPLEY"]'::jsonb, 'ARPATEL', 'India', 'All-rounder', 'T20 World Cup 2024'),
  (10, '2026-01-24', 'Sydney Cricket Ground', '185/9 (19.5 overs)', '108/9 (13.2 overs)', 'Team 1 won by 33 runs', '["MOHAMMADRIZWAN","BABARAZAM","MOHAMMADHARIS","SHANMASOOD","IFTIKHARAHMED","MOHAMMADNAWAZ","SHADABKHAN","MOHAMMADWASIM","NASEEMSHAH","HARISRAUF","SHAHEENSHAHAFRIDI","TBAVUMA","QDEKOCK","RRROSSOUW","AKMARKRAM","HKLAASEN","TSTUBBS","WDPARNELL","KRABADA","ANORTJE","LNGIDI","TSHAMSI"]'::jsonb, 'SHADABKHAN', 'Pakistan', 'All-rounder', 'T20 World Cup 2024'),
  (11, '2026-01-25', 'Wankhede Stadium', '192/2 (19.4 overs)', '196/3 (20 overs)', 'Team 2 won by 7 wickets', '["RGSHARMA","AMRAHANE","VKOHLI","MSDHONI","SKRAINA","MKPANDEY","HHPANDYA","RAJADEJA","RASHWIN","JJBUMRAH","ANEHRA","JCHARLES","CHGAYLE","MNSAMUELS","LMPSIMMONS","ADRUSSELL","DRAMDIN","DJBRAVO","DJGSAMMY","CRBRATHWAITE","SBADREE","SJBENN"]'::jsonb, 'LMPSIMMONS', 'West Indies', 'Batsman', 'T20 World Cup 2024'),
  (12, '2026-01-26', 'Daren Sammy National Cricket Stadium, Gros Islet, St Lucia', '163/6 (20 overs)', '156/6 (19.4 overs)', 'Team 1 won by 7 runs', '["RRHENDRICKS","QDEKOCK","HKLAASEN","DAMILLER","AKMARKRAM","TSTUBBS","MJANSEN","KAMAHARAJ","KRABADA","ANORTJE","OEGBAARTMAN","PDSALT","JCBUTTLER","JMBAIRSTOW","MMALI","HCBROOK","LSLIVINGSTONE","SMCURRAN","JCARCHER","AURASHID","MAWOOD","RJWTOPLEY"]'::jsonb, 'QDEKOCK', 'South Africa', 'Wicketkeeper', 'T20 World Cup 2024'),
  (13, '2026-01-27', 'Wankhede Stadium', '229/4 (19.2 overs)', '230/8 (19.2 overs)', 'Team 2 won by 2 wickets', '["JJROY","ADHALES","BASTOKES","JEROOT","EJGMORGAN","JCBUTTLER","MMALI","CJJORDAN","DJWILLEY","AURASHID","RJWTOPLEY","HMAMLA","QDEKOCK","ABDEVILLIERS","FDUPLESSIS","JPDUMINY","DAMILLER","CHMORRIS","KJABBOTT","DWSTEYN","KRABADA","IMRANTAHIR"]'::jsonb, 'JEROOT', 'England', 'Batsman', 'T20 World Cup 2024'),
  (14, '2026-01-28', 'Vidarbha Cricket Association Stadium, Jamtha', '122/8 (19.2 overs)', '123/7 (20 overs)', 'Team 2 won by 3 wickets', '["HMAMLA","QDEKOCK","FDUPLESSIS","RRROSSOUW","ABDEVILLIERS","DAMILLER","DWIESE","CHMORRIS","AMPHANGISO","KRABADA","IMRANTAHIR","JCHARLES","CHGAYLE","ADSFLETCHER","MNSAMUELS","DJBRAVO","ADRUSSELL","DJGSAMMY","CRBRATHWAITE","DRAMDIN","SBADREE","SJBENN"]'::jsonb, 'MNSAMUELS', 'West Indies', 'All-rounder', 'T20 World Cup 2024'),
  (15, '2026-01-29', 'Dubai International Cricket Stadium', '55/10 (14.5 overs)', '56/4 (8.3 overs)', 'Team 2 won by 6 wickets', '["LMPSIMMONS","ELEWIS","CHGAYLE","SOHETMYER","DJBRAVO","NPOORAN","KAPOLLARD","ADRUSSELL","AJHOSEIN","OCMCCOY","RRAMPAUL","JJROY","JCBUTTLER","JMBAIRSTOW","MMALI","LSLIVINGSTONE","EJGMORGAN","DJMALAN","CRWOAKES","CJJORDAN","AURASHID","TSMILLS"]'::jsonb, 'MMALI', 'England', 'All-rounder', 'T20 World Cup 2024'),
  (16, '2026-01-30', 'Dubai International Cricket Stadium', '143/8 (19.5 overs)', '144/2 (18.1 overs)', 'Team 2 won by 8 wickets', '["LMPSIMMONS","ELEWIS","NPOORAN","CHGAYLE","KAPOLLARD","ADRUSSELL","SOHETMYER","DJBRAVO","HRWALSH","AJHOSEIN","RRAMPAUL","TBAVUMA","RRHENDRICKS","HEVANDERDUSSEN","AKMARKRAM","DAMILLER","HKLAASEN","DPRETORIUS","KRABADA","KAMAHARAJ","ANORTJE","TSHAMSI"]'::jsonb, 'ANORTJE', 'South Africa', 'Bowler', 'T20 World Cup 2024'),
  (17, '2026-01-31', 'Sir Vivian Richards Stadium, North Sound, Antigua', '135/8 (19.2 overs)', '124/7 (17 overs)', 'Team 2 won by 3 wickets', '["KRMAYERS","SDHOPE","NPOORAN","RLCHASE","RPOWELL","SERUTHERFORD","ADRUSSELL","AJHOSEIN","ASJOSEPH","GMOTIE","OCMCCOY","QDEKOCK","RRHENDRICKS","AKMARKRAM","TSTUBBS","HKLAASEN","DAMILLER","MJANSEN","KAMAHARAJ","KRABADA","ANORTJE","TSHAMSI"]'::jsonb, 'TSHAMSI', 'South Africa', 'Bowler', 'T20 World Cup 2024'),
  (18, '2026-02-01', 'Feroz Shah Kotla', '171/4 (19.4 overs)', '161/8 (19.1 overs)', 'Team 1 won by 10 runs', '["JJROY","ADHALES","JEROOT","JCBUTTLER","EJGMORGAN","BASTOKES","MMALI","CJJORDAN","DJWILLEY","AURASHID","LEPLUNKETT","LDCHANDIMAL","TMDILSHAN","TAMSIRIWARDANA","HDRLTHIRIMANNE","ADMATHEWS","CKKAPUGEDERA","NLTCPERERA","MDSHANAKA","HMRKBHERATH","JDFVANDERSAY","PVDCHAMEERA"]'::jsonb, 'JCBUTTLER', 'England', 'Wicketkeeper', 'T20 World Cup 2024'),
  (19, '2026-02-02', 'Feroz Shah Kotla', '153/8 (20 overs)', '159/3 (17.2 overs)', 'Team 2 won by 7 wickets', '["JJROY","ADHALES","JEROOT","EJGMORGAN","JCBUTTLER","BASTOKES","MMALI","CJJORDAN","DJWILLEY","AURASHID","LEPLUNKETT","MJGUPTILL","KSWILLIAMSON","CMUNRO","CJANDERSON","LRPLTAYLOR","LRONCHI","GDELLIOTT","MJSANTNER","MJMCCLENAGHAN","ISSODHI","AFMILNE"]'::jsonb, 'JJROY', 'England', 'Batsman', 'T20 World Cup 2024'),
  (20, '2026-02-03', 'Sharjah Cricket Stadium', '134/8 (19.2 overs)', '135/5 (18.2 overs)', 'Team 2 won by 5 wickets', '["MJGUPTILL","DJMITCHELL","KSWILLIAMSON","JDSNEESHAM","DPCONWAY","GDPHILLIPS","TLSEIFERT","MJSANTNER","ISSODHI","TGSOUTHEE","TABOULT","MOHAMMADRIZWAN","BABARAZAM","FAKHARZAMAN","MOHAMMADHAFEEZ","SHOAIBMALIK","IMADWASIM","ASIFALI","SHADABKHAN","HASANALI","HARISRAUF","SHAHEENSHAHAFRIDI"]'::jsonb, 'HARISRAUF', 'Pakistan', 'Bowler', 'T20 World Cup 2024'),
  (21, '2026-02-04', 'Adelaide Oval', '184/6 (19.5 overs)', '145/6 (15.1 overs)', 'Team 1 won by 5 runs', '["KLRAHUL","RGSHARMA","VKOHLI","SAYADAV","HHPANDYA","KDKARTHIK","ARPATEL","RASHWIN","BKUMAR","MOHAMMEDSHAMI","ARSHDEEPSINGH","NAZMULHOSSAINSHANTO","LITONDAS","SHAKIBALHASAN","AFIFHOSSAIN","YASIRALICHOWDHURY","NURULHASAN","MOSADDEKHOSSAIN","TASKINAHMED","HASANMAHMUD","SHORIFULISLAM","MUSTAFIZURRAHMAN"]'::jsonb, 'VKOHLI', 'India', 'Batsman', 'T20 World Cup 2024'),
  (22, '2026-02-05', 'Adelaide Oval', '127/8 (19.1 overs)', '128/5 (18.5 overs)', 'Team 2 won by 5 wickets', '["NAZMULHOSSAINSHANTO","LITONDAS","SOUMYASARKAR","SHAKIBALHASAN","AFIFHOSSAIN","MOSADDEKHOSSAIN","NURULHASAN","TASKINAHMED","NASUMAHMED","MUSTAFIZURRAHMAN","EBADATHOSSAIN","MOHAMMADRIZWAN","BABARAZAM","MOHAMMADNAWAZ","MOHAMMADHARIS","SHANMASOOD","IFTIKHARAHMED","SHADABKHAN","MOHAMMADWASIM","NASEEMSHAH","HARISRAUF","SHAHEENSHAHAFRIDI"]'::jsonb, 'SHAHEENSHAHAFRIDI', 'Pakistan', 'Bowler', 'T20 World Cup 2024'),
  (23, '2026-02-06', 'Sydney Cricket Ground', '152/4 (20 overs)', '153/3 (19.4 overs)', 'Team 2 won by 7 wickets', '["FHALLEN","DPCONWAY","KSWILLIAMSON","GDPHILLIPS","DJMITCHELL","JDSNEESHAM","MJSANTNER","TGSOUTHEE","ISSODHI","LHFERGUSON","TABOULT","MOHAMMADRIZWAN","BABARAZAM","MOHAMMADHARIS","SHANMASOOD","IFTIKHARAHMED","MOHAMMADNAWAZ","SHADABKHAN","MOHAMMADWASIM","NASEEMSHAH","HARISRAUF","SHAHEENSHAHAFRIDI"]'::jsonb, 'MOHAMMADRIZWAN', 'Pakistan', 'Wicketkeeper', 'T20 World Cup 2024'),
  (24, '2026-02-07', 'Sir Vivian Richards Stadium, North Sound, Antigua', '196/5 (19.1 overs)', '146/8 (19.3 overs)', 'Team 1 won by 50 runs', '["RGSHARMA","VKOHLI","RRPANT","SAYADAV","SDUBE","HHPANDYA","ARPATEL","RAJADEJA","ARSHDEEPSINGH","KULDEEPYADAV","JJBUMRAH","LITONDAS","TANZIDHASAN","NAZMULHOSSAINSHANTO","TOWHIDHRIDOY","SHAKIBALHASAN","MAHMUDULLAH","JAKERALI","RISHADHOSSAIN","MAHEDIHASAN","TANZIMHASANSAKIB","MUSTAFIZURRAHMAN"]'::jsonb, 'HHPANDYA', 'India', 'All-rounder', 'T20 World Cup 2024'),
  (25, '2026-02-08', 'Daren Sammy National Cricket Stadium, Gros Islet, St Lucia', '205/5 (19.2 overs)', '181/7 (19.3 overs)', 'Team 1 won by 24 runs', '["RGSHARMA","VKOHLI","RRPANT","SAYADAV","SDUBE","HHPANDYA","RAJADEJA","ARPATEL","KULDEEPYADAV","ARSHDEEPSINGH","JJBUMRAH","DAWARNER","TMHEAD","MRMARSH","GJMAXWELL","MPSTOINIS","THDAVID","MSWADE","PJCUMMINS","MASTARC","AZAMPA","JRHAZLEWOOD"]'::jsonb, 'RGSHARMA', 'India', 'Batsman', 'T20 World Cup 2024'),
  (26, '2026-02-09', 'Shere Bangla National Stadium', '166/6 (19.5 overs)', '82/10 (17.1 overs)', 'Team 1 won by 84 runs', '["AHMEDSHEHZAD","KAMRANAKMAL","MOHAMMADHAFEEZ","UMARAKMAL","SHOAIBMALIK","SOHAIBMAQSOOD","SHAHIDAFRIDI","SOHAILTANVIR","UMARGUL","SAEEDAJMAL","ZULFIQARBABAR","DRSMITH","CHGAYLE","LMPSIMMONS","MNSAMUELS","DJBRAVO","DRAMDIN","DJGSAMMY","ADRUSSELL","SPNARINE","SBADREE","KSANTOKIE"]'::jsonb, 'DJBRAVO', 'West Indies', 'All-rounder', 'T20 World Cup 2024'),
  (27, '2026-02-10', 'Nassau County International Cricket Stadium, New York', '77/10 (19.4 overs)', '80/4 (16.5 overs)', 'Team 2 won by 6 wickets', '["PNISSANKA","BKGMENDIS","PHKDMENDIS","PWHDESILVA","SSAMARAWICKRAMA","KICASALANKA","ADMATHEWS","MDSHANAKA","MTHEEKSHANA","MPATHIRANA","NTHUSHARA","QDEKOCK","RRHENDRICKS","AKMARKRAM","TSTUBBS","HKLAASEN","DAMILLER","MJANSEN","KAMAHARAJ","KRABADA","ANORTJE","OEGBAARTMAN"]'::jsonb, 'ANORTJE', 'South Africa', 'Bowler', 'T20 World Cup 2024'),
  (28, '2026-02-11', 'Nassau County International Cricket Stadium, New York', '113/6 (19.3 overs)', '109/7 (20 overs)', 'Team 1 won by 4 runs', '["RRHENDRICKS","QDEKOCK","AKMARKRAM","TSTUBBS","HKLAASEN","DAMILLER","MJANSEN","KAMAHARAJ","KRABADA","ANORTJE","OEGBAARTMAN","TANZIDHASAN","NAZMULHOSSAINSHANTO","LITONDAS","SHAKIBALHASAN","TOWHIDHRIDOY","MAHMUDULLAH","JAKERALI","RISHADHOSSAIN","TASKINAHMED","TANZIMHASANSAKIB","MUSTAFIZURRAHMAN"]'::jsonb, 'HKLAASEN', 'South Africa', 'Wicketkeeper', 'T20 World Cup 2024'),
  (29, '2026-02-12', 'Brisbane Cricket Ground, Woolloongabba, Brisbane', '179/6 (19.2 overs)', '159/6 (19.4 overs)', 'Team 1 won by 20 runs', '["JCBUTTLER","ADHALES","MMALI","LSLIVINGSTONE","HCBROOK","BASTOKES","SMCURRAN","DJMALAN","CRWOAKES","MAWOOD","AURASHID","FHALLEN","DPCONWAY","KSWILLIAMSON","GDPHILLIPS","JDSNEESHAM","DJMITCHELL","MJSANTNER","ISSODHI","TGSOUTHEE","LHFERGUSON","TABOULT"]'::jsonb, 'JCBUTTLER', 'England', 'Wicketkeeper', 'T20 World Cup 2024'),
  (30, '2026-02-13', 'Sydney Cricket Ground', '141/8 (19.2 overs)', '144/6 (19.2 overs)', 'Team 2 won by 4 wickets', '["PNISSANKA","BKGMENDIS","DMDESILVA","KICASALANKA","PBBRAJAPAKSA","MDSHANAKA","PWHDESILVA","CKARUNARATNE","MTHEEKSHANA","CAKRAJITHA","CBRLSKUMARA","JCBUTTLER","ADHALES","BASTOKES","HCBROOK","LSLIVINGSTONE","MMALI","SMCURRAN","CRWOAKES","DJMALAN","MAWOOD","AURASHID"]'::jsonb, 'AURASHID', 'England', 'Bowler', 'T20 World Cup 2024'),
  (31, '2026-02-14', 'Daren Sammy National Cricket Stadium, Gros Islet, St Lucia', '180/5 (19.4 overs)', '181/2 (17.3 overs)', 'Team 2 won by 8 wickets', '["BAKING","JCHARLES","NPOORAN","RPOWELL","ADRUSSELL","SERUTHERFORD","RSHEPHERD","RLCHASE","AJHOSEIN","ASJOSEPH","GMOTIE","PDSALT","JCBUTTLER","MMALI","JMBAIRSTOW","HCBROOK","LSLIVINGSTONE","SMCURRAN","JCARCHER","AURASHID","MAWOOD","RJWTOPLEY"]'::jsonb, 'PDSALT', 'England', 'Wicketkeeper', 'T20 World Cup 2024'),
  (32, '2026-02-15', 'Shere Bangla National Stadium', '178/8 (19.2 overs)', '179/4 (20 overs)', 'Team 2 won by 6 wickets', '["AJFINCH","DAWARNER","SRWATSON","GJMAXWELL","GJBAILEY","BJHODGE","JPFAULKNER","BJHADDIN","MASTARC","JMMUIRHEAD","DEBOLLINGER","DRSMITH","CHGAYLE","LMPSIMMONS","MNSAMUELS","DJBRAVO","DJGSAMMY","DRAMDIN","ADRUSSELL","SPNARINE","SBADREE","KSANTOKIE"]'::jsonb, 'DJGSAMMY', 'West Indies', 'All-rounder', 'T20 World Cup 2024'),
  (33, '2026-02-16', 'Eden Gardens', '118/5 (17.2 overs)', '119/4 (16 overs)', 'Team 2 won by 6 wickets', '["RGSHARMA","SDHAWAN","VKOHLI","SKRAINA","YUVRAJSINGH","MSDHONI","HHPANDYA","RAJADEJA","RASHWIN","JJBUMRAH","ANEHRA","SHARJEELKHAN","AHMEDSHEHZAD","SHAHIDAFRIDI","UMARAKMAL","SHOAIBMALIK","SARFRAZAHMED","MOHAMMADHAFEEZ","MOHAMMADSAMI","WAHABRIAZ","MOHAMMADAMIR","MOHAMMADIRFAN"]'::jsonb, 'VKOHLI', 'India', 'Batsman', 'T20 World Cup 2024'),
  (34, '2026-02-17', 'Zayed Cricket Stadium, Abu Dhabi', '124/9 (19.4 overs)', '126/2 (15 overs)', 'Team 2 won by 8 wickets', '["LITONDAS","MOHAMMADNAIM","SHAKIBALHASAN","MUSHFIQURRAHIM","MAHMUDULLAH","AFIFHOSSAIN","NURULHASAN","MAHEDIHASAN","NASUMAHMED","MUSTAFIZURRAHMAN","SHORIFULISLAM","JJROY","JCBUTTLER","DJMALAN","JMBAIRSTOW","EJGMORGAN","LSLIVINGSTONE","MMALI","CRWOAKES","CJJORDAN","AURASHID","TSMILLS"]'::jsonb, 'JJROY', 'England', 'Batsman', 'T20 World Cup 2024'),
  (35, '2026-02-18', 'Sharjah Cricket Stadium', '142/10 (19.2 overs)', '146/6 (19.2 overs)', 'Team 2 won by 4 wickets', '["PNISSANKA","MDKJPERERA","KICASALANKA","PBBRAJAPAKSA","WIAFERNANDO","PWHDESILVA","MDSHANAKA","CKARUNARATNE","PVDCHAMEERA","MTHEEKSHANA","CBRLSKUMARA","QDEKOCK","RRHENDRICKS","HEVANDERDUSSEN","TBAVUMA","AKMARKRAM","DAMILLER","DPRETORIUS","KRABADA","KAMAHARAJ","ANORTJE","TSHAMSI"]'::jsonb, 'TSHAMSI', 'South Africa', 'Bowler', 'T20 World Cup 2024'),
  (36, '2026-02-19', 'Dubai International Cricket Stadium', '125/10 (19.3 overs)', '126/2 (11.2 overs)', 'Team 2 won by 8 wickets', '["DAWARNER","AJFINCH","SPDSMITH","GJMAXWELL","MPSTOINIS","MSWADE","ACAGAR","PJCUMMINS","MASTARC","AZAMPA","JRHAZLEWOOD","JJROY","JCBUTTLER","DJMALAN","JMBAIRSTOW","EJGMORGAN","LSLIVINGSTONE","MMALI","CRWOAKES","CJJORDAN","AURASHID","TSMILLS"]'::jsonb, 'CJJORDAN', 'England', 'Bowler', 'T20 World Cup 2024'),
  (37, '2026-02-20', 'Sharjah Cricket Stadium', '163/4 (19.5 overs)', '137/10 (18.1 overs)', 'Team 1 won by 26 runs', '["JJROY","JCBUTTLER","DJMALAN","JMBAIRSTOW","EJGMORGAN","MMALI","LSLIVINGSTONE","CRWOAKES","CJJORDAN","AURASHID","TSMILLS","PNISSANKA","MDKJPERERA","KICASALANKA","WIAFERNANDO","PBBRAJAPAKSA","MDSHANAKA","PWHDESILVA","CKARUNARATNE","PVDCHAMEERA","MTHEEKSHANA","CBRLSKUMARA"]'::jsonb, 'JCBUTTLER', 'England', 'Wicketkeeper', 'T20 World Cup 2024'),
  (38, '2026-02-21', 'Zayed Cricket Stadium, Abu Dhabi', '84/10 (18.2 overs)', '86/4 (14 overs)', 'Team 2 won by 6 wickets', '["MOHAMMADNAIM","LITONDAS","SOUMYASARKAR","MUSHFIQURRAHIM","MAHMUDULLAH","AFIFHOSSAIN","SHAMIMHOSSAIN","MAHEDIHASAN","TASKINAHMED","NASUMAHMED","SHORIFULISLAM","QDEKOCK","RRHENDRICKS","HEVANDERDUSSEN","AKMARKRAM","TBAVUMA","DAMILLER","DPRETORIUS","KRABADA","KAMAHARAJ","ANORTJE","TSHAMSI"]'::jsonb, 'KRABADA', 'South Africa', 'Bowler', 'T20 World Cup 2024'),
  (39, '2026-02-22', 'Shere Bangla National Stadium', '172/4 (19.4 overs)', '176/4 (19.4 overs)', 'Team 2 won by 6 wickets', '["RGSHARMA","AMRAHANE","VKOHLI","YUVRAJSINGH","SKRAINA","MSDHONI","RASHWIN","RAJADEJA","AMISHRA","BKUMAR","MMSHARMA","QDEKOCK","HMAMLA","FDUPLESSIS","JPDUMINY","ABDEVILLIERS","DAMILLER","JAMORKEL","DWSTEYN","BEHENDRICKS","IMRANTAHIR","WDPARNELL"]'::jsonb, 'VKOHLI', 'India', 'Batsman', 'T20 World Cup 2024'),
  (40, '2026-02-23', 'Shere Bangla National Stadium', '138/7 (19.2 overs)', '141/2 (18.2 overs)', 'Team 2 won by 8 wickets', '["TAMIMIQBAL","ANAMULHAQUE","SHAMSURRAHMAN","SHAKIBALHASAN","MUSHFIQURRAHIM","NASIRHOSSAIN","MAHMUDULLAH","ZIAURRAHMAN","MASHRAFEMORTAZA","SOHAGGAZI","ALAMINHOSSAIN","RGSHARMA","SDHAWAN","VKOHLI","MSDHONI","SKRAINA","YUVRAJSINGH","RASHWIN","RAJADEJA","AMISHRA","BKUMAR","MOHAMMEDSHAMI"]'::jsonb, 'RASHWIN', 'India', 'All-rounder', 'T20 World Cup 2024'),
  (41, '2026-02-24', 'M Chinnaswamy Stadium', '146/7 (19.1 overs)', '145/9 (19.1 overs)', 'Team 1 won by 1 runs', '["RGSHARMA","SDHAWAN","VKOHLI","SKRAINA","HHPANDYA","MSDHONI","YUVRAJSINGH","RAJADEJA","RASHWIN","ANEHRA","JJBUMRAH","TAMIMIQBAL","MOHAMMADMITHUN","SABBIRRAHMAN","SHAKIBALHASAN","MASHRAFEMORTAZA","MAHMUDULLAH","SOUMYASARKAR","MUSHFIQURRAHIM","SHUVAGATAHOM","MUSTAFIZURRAHMAN","ALAMINHOSSAIN"]'::jsonb, 'RASHWIN', 'India', 'All-rounder', 'T20 World Cup 2024'),
  (42, '2026-02-25', 'Punjab Cricket Association IS Bindra Stadium, Mohali', '160/6 (19.2 overs)', '161/4 (19.3 overs)', 'Team 2 won by 6 wickets', '["RGSHARMA","SDHAWAN","VKOHLI","SKRAINA","YUVRAJSINGH","MSDHONI","HHPANDYA","RAJADEJA","RASHWIN","ANEHRA","JJBUMRAH","UTKHAWAJA","AJFINCH","DAWARNER","SPDSMITH","GJMAXWELL","SRWATSON","JPFAULKNER","PMNEVILL","AZAMPA","NMCOULTERNILE","JRHAZLEWOOD"]'::jsonb, 'VKOHLI', 'India', 'Batsman', 'T20 World Cup 2024'),
  (43, '2026-02-26', 'Zahur Ahmed Chowdhury Stadium', '189/4 (20 overs)', '190/4 (20 overs)', 'Team 2 won by 6 wickets', '["MJLUMB","ADHALES","MMALI","EJGMORGAN","JCBUTTLER","RSBOPARA","TTBRESNAN","CJJORDAN","SCJBROAD","JCTREDWELL","JWDERNBACH","TMDILSHAN","MDKJPERERA","DPMDJAYAWARDENE","NLTCPERERA","KCSANGAKKARA","ADMATHEWS","LDCHANDIMAL","KMDNKULASEKARA","SMSMSENANAYAKE","BAWMENDIS","SLMALINGA"]'::jsonb, 'ADHALES', 'England', 'Batsman', 'T20 World Cup 2024'),
  (44, '2026-02-27', 'Shere Bangla National Stadium', '159/7 (19.3 overs)', '86/10 (16.3 overs)', 'Team 1 won by 73 runs', '["AJFINCH","DAWARNER","CLWHITE","SRWATSON","GJMAXWELL","GJBAILEY","BJHODGE","BJHADDIN","MASTARC","JMMUIRHEAD","DEBOLLINGER","RGSHARMA","AMRAHANE","VKOHLI","YUVRAJSINGH","SKRAINA","MSDHONI","RAJADEJA","RASHWIN","BKUMAR","AMISHRA","MMSHARMA"]'::jsonb, 'RASHWIN', 'India', 'All-rounder', 'T20 World Cup 2024'),
  (45, '2026-02-28', 'Zayed Cricket Stadium, Abu Dhabi', '189/2 (20 overs)', '144/5 (19.2 overs)', 'Team 1 won by 45 runs', '["MOHAMMADRIZWAN","BABARAZAM","FAKHARZAMAN","MOHAMMADHAFEEZ","SHOAIBMALIK","ASIFALI","SHADABKHAN","IMADWASIM","HASANALI","HARISRAUF","SHAHEENSHAHAFRIDI","SJBAARD","MVANLINGEN","CGWILLIAMS","MGERASMUS","DWIESE","JJSMIT","JNLOFTIEEATON","RTRUMPELMANN","ZEGREEN","JNFRYLINCK","BSHIKONGO"]'::jsonb, 'MOHAMMADRIZWAN', 'Pakistan', 'Wicketkeeper', 'T20 World Cup 2024'),
  (46, '2026-03-01', 'Dubai International Cricket Stadium', '85/10 (18 overs)', '89/2 (6.4 overs)', 'Team 2 won by 8 wickets', '["HGMUNSEY","KJCOETZER","MHCROSS","RDBERRINGTON","CSMACLEOD","MALEASK","CNGREAVES","MRJWATT","SMSHARIF","ACEVANS","BTJWHEAL","KLRAHUL","RGSHARMA","VKOHLI","SAYADAV","RRPANT","HHPANDYA","RAJADEJA","RASHWIN","MOHAMMEDSHAMI","JJBUMRAH","CVVARUN"]'::jsonb, 'RAJADEJA', 'India', 'All-rounder', 'T20 World Cup 2024'),
  (47, '2026-03-02', 'Sharjah Cricket Stadium', '189/4 (19.1 overs)', '117/6 (19.4 overs)', 'Team 1 won by 72 runs', '["MOHAMMADRIZWAN","BABARAZAM","FAKHARZAMAN","MOHAMMADHAFEEZ","SHOAIBMALIK","ASIFALI","SHADABKHAN","IMADWASIM","HASANALI","HARISRAUF","SHAHEENSHAHAFRIDI","HGMUNSEY","KJCOETZER","MHCROSS","RDBERRINGTON","DEBUDGE","MALEASK","CNGREAVES","MRJWATT","SMSHARIF","BTJWHEAL","HAMZATAHIR"]'::jsonb, 'SHOAIBMALIK', 'Pakistan', 'All-rounder', 'T20 World Cup 2024'),
  (48, '2026-03-03', 'Sydney Cricket Ground', '179/2 (19.3 overs)', '123/9 (19.4 overs)', 'Team 1 won by 56 runs', '["KLRAHUL","RGSHARMA","VKOHLI","SAYADAV","ARPATEL","HHPANDYA","KDKARTHIK","RASHWIN","MOHAMMEDSHAMI","BKUMAR","ARSHDEEPSINGH","VIKRAMJITSINGH","MPODOWD","BFWDELEEDE","CNACKERMANN","TLWCOOPER","SAEDWARDS","TJGPRINGLE","LVVANBEEK","SHARIZAHMAD","FJKLAASSEN","PAVANMEEKEREN"]'::jsonb, 'SAYADAV', 'India', 'Batsman', 'T20 World Cup 2024'),
  (49, '2026-03-04', 'Melbourne Cricket Ground', '186/5 (20 overs)', '115/10 (17.3 overs)', 'Team 1 won by 71 runs', '["KLRAHUL","RGSHARMA","VKOHLI","SAYADAV","RRPANT","HHPANDYA","ARPATEL","RASHWIN","BKUMAR","MOHAMMEDSHAMI","ARSHDEEPSINGH","WMADHEVERE","CRERVINE","RWCHAKABVA","SCWILLIAMS","SIKANDARRAZA","TMUNYONGA","RPBURL","WPMASAKADZA","RNGARAVA","TLCHATARA","BMUZARABANI"]'::jsonb, 'SAYADAV', 'India', 'Batsman', 'T20 World Cup 2024'),
  (50, '2026-03-05', 'Sir Vivian Richards Stadium, North Sound, Antigua', '194/4 (20 overs)', '176/6 (19.1 overs)', 'Team 1 won by 18 runs', '["QDEKOCK","RRHENDRICKS","AKMARKRAM","DAMILLER","HKLAASEN","TSTUBBS","MJANSEN","KAMAHARAJ","KRABADA","ANORTJE","TSHAMSI","SRTAYLOR","AGSGOUS","NRKUMAR","AARONJONES","CJANDERSON","SHAYANJAHANGIR","HARMEETSINGH","JASDEEPSINGH","NPKENJIGE","ALIKHAN","SNNETRAVALKAR"]'::jsonb, 'QDEKOCK', 'South Africa', 'Wicketkeeper', 'T20 World Cup 2024'),
  (51, '2026-03-06', 'Perth Stadium', '91/10 (19.2 overs)', '95/4 (13.5 overs)', 'Team 2 won by 6 wickets', '["SJMYBURGH","MPODOWD","BFWDELEEDE","TLWCOOPER","CNACKERMANN","SAEDWARDS","REVANDERMERWE","TJGPRINGLE","LVVANBEEK","FJKLAASSEN","PAVANMEEKEREN","BDGLOVER","MOHAMMADRIZWAN","BABARAZAM","FAKHARZAMAN","SHANMASOOD","IFTIKHARAHMED","SHADABKHAN","MOHAMMADNAWAZ","MOHAMMADWASIM","SHAHEENSHAHAFRIDI","HARISRAUF","NASEEMSHAH"]'::jsonb, 'SHADABKHAN', 'Pakistan', 'All-rounder', 'T20 World Cup 2024'),
  (52, '2026-03-07', 'Dubai International Cricket Stadium', '132/8 (19.5 overs)', '136/1 (15.2 overs)', 'Team 2 won by 9 wickets', '["SJBAARD","MVANLINGEN","CGWILLIAMS","MGERASMUS","JNLOFTIEEATON","DWIESE","JJSMIT","ZEGREEN","JNFRYLINCK","RTRUMPELMANN","BMSCHOLTZ","KLRAHUL","RGSHARMA","SAYADAV","VKOHLI","RRPANT","HHPANDYA","RAJADEJA","RASHWIN","MOHAMMEDSHAMI","JJBUMRAH","RDCHAHAR"]'::jsonb, 'RAJADEJA', 'India', 'All-rounder', 'T20 World Cup 2024'),
  (53, '2026-03-08', 'Nassau County International Cricket Stadium, New York', '96/10 (16 overs)', '97/3 (12.2 overs)', 'Team 2 won by 8 wickets', '["ABALBIRNIE","PRSTIRLING","LTUCKER","HTTECTOR","CCAMPHER","GHDOCKRELL","GJDELANY","MRADAIR","BJMCCARTHY","JLITTLE","BWHITE","RGSHARMA","VKOHLI","RRPANT","SAYADAV","SDUBE","HHPANDYA","RAJADEJA","ARPATEL","JJBUMRAH","ARSHDEEPSINGH","MOHAMMEDSIRAJ"]'::jsonb, 'JJBUMRAH', 'India', 'Bowler', 'T20 World Cup 2024'),
  (54, '2026-03-09', 'Nassau County International Cricket Stadium, New York', '103/9 (19.1 overs)', '106/6 (18.2 overs)', 'Team 2 won by 4 wickets', '["MLEVITT","MPODOWD","VIKRAMJITSINGH","SAENGELBRECHT","BFWDELEEDE","SAEDWARDS","ATNIDAMANURU","LVVANBEEK","TJGPRINGLE","PAVANMEEKEREN","VJKINGMA","RRHENDRICKS","QDEKOCK","AKMARKRAM","TSTUBBS","HKLAASEN","DAMILLER","MJANSEN","KAMAHARAJ","KRABADA","ANORTJE","OEGBAARTMAN"]'::jsonb, 'DAMILLER', 'South Africa', 'Batsman', 'T20 World Cup 2024'),
  (55, '2026-03-10', 'Nassau County International Cricket Stadium, New York', '110/8 (19.3 overs)', '111/3 (18.5 overs)', 'Team 2 won by 7 wickets', '["SHAYANJAHANGIR","SRTAYLOR","AGSGOUS","AARONJONES","NRKUMAR","CJANDERSON","HARMEETSINGH","SCVANSCHALKWYK","JASDEEPSINGH","SNNETRAVALKAR","ALIKHAN","RGSHARMA","VKOHLI","RRPANT","SAYADAV","SDUBE","HHPANDYA","RAJADEJA","ARPATEL","ARSHDEEPSINGH","JJBUMRAH","MOHAMMEDSIRAJ"]'::jsonb, 'ARSHDEEPSINGH', 'India', 'Bowler', 'T20 World Cup 2024'),
  (56, '2026-03-11', 'Arnos Vale Ground, Kingstown, St Vincent', '115/7 (19.3 overs)', '114/7 (19.4 overs)', 'Team 1 won by 1 runs', '["RRHENDRICKS","QDEKOCK","AKMARKRAM","HKLAASEN","DAMILLER","TSTUBBS","MJANSEN","KRABADA","ANORTJE","OEGBAARTMAN","TSHAMSI","KBHURTEL","AASIFSHEIKH","RKPAUDEL","AKSAH","DSAIREE","KUSHALMALLA","GULSANJHA","SOMPALKAMI","KARANKC","SLAMICHHANE","ABOHARA"]'::jsonb, 'TSHAMSI', 'South Africa', 'Bowler', 'T20 World Cup 2024'),
  (57, '2026-03-12', 'Sir Vivian Richards Stadium, North Sound, Antigua', '122/5 (9.1 overs)', '84/3 (9.3 overs)', 'Team 1 won by 41 runs', '["PDSALT","JCBUTTLER","JMBAIRSTOW","HCBROOK","MMALI","LSLIVINGSTONE","SMCURRAN","JCARCHER","AURASHID","CJJORDAN","RJWTOPLEY","MVANLINGEN","NDAVIN","DWIESE","MGERASMUS","JJSMIT","JNFRYLINCK","ZEGREEN","RTRUMPELMANN","BMSCHOLTZ","JTBRASSELL","JPKOTZE"]'::jsonb, 'HCBROOK', 'England', 'Batsman', 'T20 World Cup 2024'),
  (58, '2026-03-13', 'Kensington Oval, Bridgetown, Barbados', '115/10 (19 overs)', '117/0 (9.3 overs)', 'Team 2 won by 10 wickets', '["SRTAYLOR","AGSGOUS","NRKUMAR","AARONJONES","CJANDERSON","MILINDKUMAR","HARMEETSINGH","SCVANSCHALKWYK","ALIKHAN","NPKENJIGE","SNNETRAVALKAR","PDSALT","JCBUTTLER","JMBAIRSTOW","HCBROOK","MMALI","LSLIVINGSTONE","SMCURRAN","CJJORDAN","JCARCHER","AURASHID","RJWTOPLEY"]'::jsonb, 'AURASHID', 'England', 'Bowler', 'T20 World Cup 2024'),
  (59, '2026-03-14', 'Central Broward Regional Park Stadium Turf Ground, Lauderhill', '106/9 (19.3 overs)', '111/7 (18.2 overs)', 'Team 2 won by 3 wickets', '["ABALBIRNIE","PRSTIRLING","LTUCKER","HTTECTOR","CCAMPHER","GHDOCKRELL","GJDELANY","MRADAIR","BJMCCARTHY","JLITTLE","BWHITE","MOHAMMADRIZWAN","SAIMAYUB","BABARAZAM","FAKHARZAMAN","USMANKHAN","SHADABKHAN","IMADWASIM","ABBASAFRIDI","SHAHEENSHAHAFRIDI","HARISRAUF","MOHAMMADAMIR"]'::jsonb, 'SHAHEENSHAHAFRIDI', 'Pakistan', 'Bowler', 'T20 World Cup 2024'),
  (60, '2026-03-15', 'Sir Vivian Richards Stadium, North Sound, Antigua', '47/10 (14 overs)', '50/2 (3.2 overs)', 'Team 2 won by 8 wickets', '["PSATHAVALE","KHPRAJAPATI","AQIBILYAS","ZEESHANMAQSOOD","KHALIDKAIL","AYANKHAN","SHOAIBKHAN","MEHRANKHAN","FAYYAZBUTT","KALEEMULLAH","BILALKHAN","PDSALT","JCBUTTLER","WGJACKS","JMBAIRSTOW","HCBROOK","MMALI","LSLIVINGSTONE","JCARCHER","AURASHID","MAWOOD","RJWTOPLEY"]'::jsonb, 'AURASHID', 'England', 'Bowler', 'T20 World Cup 2024');